--------------------Indra-----------------------------

UPDATE `common_automation_document_action_config` SET `action_id`='3' WHERE  `id`=62;

ALTER TABLE `common_notification_email_template`
	CHANGE COLUMN `event_id` `event_id` INT(15) NULL AFTER `template_data`;
	
ALTER TABLE `common_notification_mst`
	CHANGE COLUMN `reference_no` `reference_no` VARCHAR(50) NULL COLLATE 'latin1_swedish_ci' AFTER `description`,
	CHANGE COLUMN `reference_id` `reference_id` INT(11) NULL AFTER `reference_no`,
	CHANGE COLUMN `reference_status` `reference_status` CHAR(1) NULL DEFAULT '' COLLATE 'latin1_swedish_ci' AFTER `reference_id`,
	CHANGE COLUMN `notification_type_id` `notification_type_id` INT(11) NULL AFTER `to_user`,
	CHANGE COLUMN `event_id` `event_id` INT(11) NULL AFTER `notification_type_id`;
	
INSERT INTO `common_notification_email_template` (`id`, `template_name`, `subject`, `template_data`, `event_id`, `status`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (22, 'AUTOMATION_EMAIL_TEMPLATE', 'Automation email', '<html> <head>     <meta charset="UTF-8">     <meta name="viewport" content="width=device-width, initial-scale=1.0"> </head>  <body> 	<table style="color: #207580;"> 	 	<tr>        <td style="font-weight: bold">Dear <span id="EMAIL_ADDRESS">Email address</span>,</td>     </tr> 	<tr style="height:20px"><tr> 	<tr>      <td>  	 <span id="EMAIL_CONTENT" >Email Content here</span> 	 </td>     </tr> 	<tr style="height:10px"><tr> 	<tr>                 <td>If you have any comments or questions, please do not hesitate to contact us at <span style="font-weight: bold"><a href="mailto:support@papertrl.com">support@papertrl.com.</a></span></td>     </tr> 	 	<tr style="line-height: 70px;">                 <td>                     <span style="font-weight: bold">Thank You!</span>                 </td>             </tr>             <tr>                 <td>                     <img style="width: 170px;height: 45px;" src="https://papertrl.com/wp-content/uploads/2019/09/logo.png"/>                 </td>             </tr>             <tr>                 <td>This email is an automated notification, Replies to this message will not be read or responded to. We\'re happy to help you with any questions or concerns you may have. Please contact us directly 24/7 via <span style="font-weight: bold">support@papertrl.com</span>                     <p class="MsoNormal"><span style="font-size:8.0pt;color:#207580">CONFIDENTIALITY NOTICE: This e-mail transmission, and any attachments, is intended only for the use of PaperTrl Inc. or recipient named above and may contain information that                             is confidential, privileged and exempt from disclosure under applicable law. If you are not the intended recipient or authorized to receive this message for the recipient, you must not use, copy, disclose or take any action based on this message or any information                             herein. If you have received this message in error, please advise the sender immediately.</span><span style="font-size:8.0pt;color:#014708"></span></p>                     <p><span style="font-size:18.0pt;font-family:Webdings;color:green">P</span><span style="color:black">                         </span><span style="font-size:10.0pt;font-family:&quot;Helvetica&quot;,sans-serif;color:green">Be Environmentally Responsible. Please don\'t print this e-mail unless you really need to.</span><u></u><u></u></p>                 </td>             </tr> 	 	 	<table>  </body> </html>', NULL, 'A', 'admin', '2021-08-04', NULL, NULL, NULL, NULL);

