INSERT INTO `common_grid_template`(`id`, `grid_name`) VALUES (65, 'VENDOR_TRANSACTION_LIST');

INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.txnRef', 'Ref No.', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'input', 'Ref No.', 2, NULL, 160, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.batchNo', 'Batch No.', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'input', 'Batch No.', 3, NULL, 160, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.documentNo', 'Bill No.', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'input', 'Bill No.', 4, NULL, 160, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.payeeName', 'Vendor', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'input', 'Vendor', 5, NULL, 170, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.txnAmount', 'Amount', 1, 1, 0, 0, 1, 1, 0, NULL, 'right', 'numeric', 'Amount', 6, NULL, 140, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.createdOn', 'Created Date', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'date', 'Created Date', 7, NULL, 160, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.status', 'Approval Status', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'dropdown', 'Approval Status', 8, 34, 171, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.txnType', 'Payment Type', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'dropdown', 'Payment Type', 10, NULL, 160, 2);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.reason', 'Reason (If failed)', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'input', 'Reason (If failed)', 12, NULL, 310, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'action', NULL, 1, 0, 0, 0, 0, 0, 1, 'right', 'left', 'actionButton', '', 60, NULL, 50, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'checkbox', NULL, 1, 0, 0, 0, 0, 0, 1, 'left', 'center', 'checkbox', '', 1, NULL, 50, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.paymentStatus', 'Payment Status', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'dropdown', 'Payment Status', 9, 25, 171, NULL);
INSERT INTO `common_grid_column_template`(`grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `filter_show`, `is_frozen`, `frozen_direction`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `column_width`, `drop_down_url_id`) VALUES (65, 'txn.trxDate', 'Payment Date', 1, 1, 0, 0, 1, 1, 0, NULL, 'left', 'date', 'Payment Date', 11, NULL, 160, NULL);



INSERT INTO `common_grid_state_template`(`id`, `grid_id`, `start_from`, `total_rows`, `column_widths`) VALUES (65, 28, 0, 25, '100,210,210,210,210,210,210,210,210,210');

