ALTER TABLE vp_bill_expense_cost_distribution MODIFY description TEXT;
ALTER TABLE hst_vp_bill_expense_cost_distribution MODIFY description TEXT;
ALTER TABLE vp_recurring_bill_expense_cost_distribution MODIFY description TEXT;
ALTER TABLE common_account_number MODIFY description TEXT;