INSERT INTO `umm_privilages`(`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (84, 'Resend An Invitation', 'Resend An Invitation', 'RESEND_VENDOR_INVITATION', 'System', '2021-06-23 01:44:07', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages`(`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (85, 'Delete An Invitation', 'Delete An Invitation', 'DELETE_VENDOR_INVITATION', 'System', '2021-06-23 01:44:09', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages`(`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (86, 'Reject Vendor Request', 'Reject Vendor Request', 'REJECT_VENDOR_REQUEST', 'System', '2021-06-23 01:44:12', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages`(`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (87, 'Delete Vendor Request', 'Delete Vendor Request', 'DELETE_VENDOR_REQUEST', 'System', '2021-06-23 01:44:17', NULL, NULL, NULL, NULL);

INSERT INTO `umm_menu_privilage`(`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1004, 84, 'VENDORS_RESEND_VENDOR_INVITATION', 'System', '2021-06-23 14:55:32', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1004, 85, 'VENDORS_DELETE_VENDOR_INVITATION', 'System', '2021-06-23 14:56:06', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1004, 86, 'VENDORS_REJECT_VENDOR_REQUEST', 'System', '2021-06-23 01:40:30', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1004, 87, 'VENDORS_DELETE_VENDOR_REQUEST', 'System', '2021-06-23 15:08:00', NULL, NULL, NULL, NULL);
