UPDATE `common_grid_column_template` SET `grid_id` = 18, `field` = 'reference', `header` = 'Reference No', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Reference No', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 170;
UPDATE `common_grid_column_template` SET `grid_id` = 18, `field` = 'amount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 172;
UPDATE `common_grid_column_template` SET `grid_id` = 18, `field` = 'syncDetail.syncDateTime', `header` = 'Date', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Date', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 173;
UPDATE `common_grid_column_template` SET `grid_id` = 18, `field` = 'syncDetail.objectType', `header` = 'Data Type', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Data Type', `column_order` = 2, `drop_down_id` = 19, `drop_down_url` = NULL WHERE `id` = 174;
UPDATE `common_grid_column_template` SET `grid_id` = 19, `field` = 'checkbox', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'checkbox', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 177;
UPDATE `common_grid_column_template` SET `grid_id` = 19, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 178;
UPDATE `common_grid_column_template` SET `grid_id` = 19, `field` = 'reference', `header` = 'Reference No', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Reference No', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 179;
UPDATE `common_grid_column_template` SET `grid_id` = 19, `field` = 'amount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 181;
UPDATE `common_grid_column_template` SET `grid_id` = 19, `field` = 'syncDetail.syncDateTime', `header` = 'Date', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Date', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 182;
UPDATE `common_grid_column_template` SET `grid_id` = 19, `field` = 'syncDetail.objectType', `header` = 'Data Type', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Data Type', `column_order` = 4, `drop_down_id` = 19, `drop_down_url` = NULL WHERE `id` = 183;
UPDATE `common_grid_column_template` SET `grid_id` = 20, `field` = 'reference', `header` = 'Reference No', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Reference No', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 186;
UPDATE `common_grid_column_template` SET `grid_id` = 20, `field` = 'amount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 188;
UPDATE `common_grid_column_template` SET `grid_id` = 20, `field` = 'syncDetail.syncDateTime', `header` = 'Date', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Date', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = NULL WHERE `id` = 189;
UPDATE `common_grid_column_template` SET `grid_id` = 20, `field` = 'syncDetail.objectType', `header` = 'Data Type', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Data Type', `column_order` = 2, `drop_down_id` = 19, `drop_down_url` = NULL WHERE `id` = 190;

ALTER TABLE `vp_customer_vendor_relation` 
MODIFY COLUMN `contact_number` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '' AFTER `vendor_email`;