
UPDATE `common_grid_column_template` SET `grid_id` = 8, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 59;
UPDATE `common_grid_column_template` SET `grid_id` = 9, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 69;
UPDATE `common_grid_column_template` SET `grid_id` = 11, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 84;
UPDATE `common_grid_column_template` SET `grid_id` = 12, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 98;
UPDATE `common_grid_column_template` SET `grid_id` = 14, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 118;
UPDATE `common_grid_column_template` SET `grid_id` = 15, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 140;
UPDATE `common_grid_column_template` SET `grid_id` = 22, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 205;
UPDATE `common_grid_column_template` SET `grid_id` = 25, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 252;
UPDATE `common_grid_column_template` SET `grid_id` = 28, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 278;
UPDATE `common_grid_column_template` SET `grid_id` = 30, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 291;

UPDATE `common_integration_service_group` SET `name` = 'Purchase Orders', `visibility` = 1, `sort_order` = 5 WHERE `id` = 8;
DELETE FROM `common_grid_column_user_wice`;
