------------Dhanuddara-------2.7.18----------------

INSERT INTO `common_grid_template`(`grid_name`) VALUES ('SYNC_ACCOUNT_FAILED_PULL_LIST');
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'failRecord.referenceNumber', 'Reference No', 1, 1, 1, 1, 1, 'left', 'input', 'Name', 3, NULL, NULL);
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'incompleteDetail.objectType', 'Data Type', 1, 1, 1, 1, 1, 'left', 'dropdown', 'Object Type', 4, 19, NULL);
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'failRecord.failedDateTime', 'Date', 1, 1, 1, 1, 1, 'center', 'date', 'Date', 5, NULL, NULL);
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'failRecord.failedReason', 'Message', 1, 1, 1, 1, 1, 'left', 'input', 'Message', 7, NULL, NULL);
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'checkbox', NULL, 1, 0, 0, 0, 0, 'center', 'checkbox', '', 1, NULL, NULL);
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'action', 'Action', 1, 0, 0, 0, 0, 'center', 'actionButton', '', 2, NULL, NULL);
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'failRecord.recordStatus', 'Event', 1, 0, 1, 1, 1, 'center', 'dropdown', 'Event', 6, 31, '');
INSERT INTO `common_grid_column_template`( `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (59,'incompleteDetail.tpCompanyId', 'Company', 1, 1, 1, 1, 1, 'left', 'dropdown', 'Company', 8, NULL, '');
INSERT INTO `common_grid_state_template`( `grid_id`, `start_from`, `total_rows`, `column_widths`) VALUES (59, 0, 10, '50,210,210,210,210,210,300,210');

ALTER TABLE `common_integration_failed_record` 
ADD COLUMN `record_status` varchar(1) NULL AFTER `tp_company_id`;
