UPDATE `common_grid_state_template` SET `id`='21', `grid_id`='7', `start_from`='0', `total_rows`='10', `column_widths`='120,85,95,90,90,140' WHERE (`id`='21');
UPDATE `common_grid_state_template` SET `id`='22', `grid_id`='11', `start_from`='0', `total_rows`='10', `column_widths`='120,95,95,95,85' WHERE (`id`='22');
UPDATE `common_grid_state_template` SET `id`='23', `grid_id`='31', `start_from`='0', `total_rows`='10', `column_widths`='120,95,95,95,95' WHERE (`id`='23');
UPDATE `common_grid_state_template` SET `id`='24', `grid_id`='8', `start_from`='0', `total_rows`='10', `column_widths`='120,95,100,90,95' WHERE (`id`='24');


UPDATE `common_grid_column_template` SET `id`='199', `grid_id`='7', `field`='pBill.subAccount', `header`='Sub Account', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='multiSelect', `placeholder`='Vendor', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='199');
UPDATE `common_grid_column_template` SET `id`='201', `grid_id`='7', `field`='pBill.pendingBills', `header`='Pending', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Applicable Discount', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='201');
UPDATE `common_grid_column_template` SET `id`='202', `grid_id`='7', `field`='pBill.approvedBills', `header`='Approved', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Applicable Discount', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='202');
UPDATE `common_grid_column_template` SET `id`='203', `grid_id`='7', `field`='pBill.rejectedBills', `header`='Rejected', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Applicable Discount', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='203');
UPDATE `common_grid_column_template` SET `id`='204', `grid_id`='7', `field`='pBill.totalPayable', `header`='Total Payable', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='right', `search_type`=' ', `placeholder`='Total Payable', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='204');
UPDATE `common_grid_column_template` SET `id`='205', `grid_id`='8', `field`='pdBill.subAccount', `header`='Sub Account', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='multiSelect', `placeholder`='Sub Account', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='205');
UPDATE `common_grid_column_template` SET `id`='206', `grid_id`='8', `field`='pdBill.totalPaymenetCount', `header`='Total Payment<br>Count', `column_show`='0', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Total Payment Count', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='206');
UPDATE `common_grid_column_template` SET `id`='207', `grid_id`='8', `field`='pdBill.activePayment', `header`='Active', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Active Payments', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='207');
UPDATE `common_grid_column_template` SET `id`='208', `grid_id`='8', `field`='pdBill.voidedPayment', `header`='Void', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Void Payments', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='208');
UPDATE `common_grid_column_template` SET `id`='209', `grid_id`='8', `field`='pdBill.totalAmountOfActivePayment', `header`='Total Paid', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='right', `search_type`=' ', `placeholder`='Total Amount Of Active Payments', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='209');
UPDATE `common_grid_column_template` SET `id`='210', `grid_id`='11', `field`='pPO.subAccount', `header`='Sub Account', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='multiSelect', `placeholder`='Sub Account', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='210');
UPDATE `common_grid_column_template` SET `id`='211', `grid_id`='11', `field`='pPO.submittedPo', `header`='Pending', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Pending Purchase Orders', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='211');
UPDATE `common_grid_column_template` SET `id`='212', `grid_id`='11', `field`='pPO.approvedPo', `header`='Approved', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Approved Purchase Orders', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='212');
UPDATE `common_grid_column_template` SET `id`='213', `grid_id`='11', `field`='pPO.rejectedPo', `header`='Rejected', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Rejected Purchase Orders', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='213');
UPDATE `common_grid_column_template` SET `id`='214', `grid_id`='11', `field`='pPO.totalPayable', `header`='Total Payable', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='right', `search_type`=' ', `placeholder`='Total Payable', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='214');
UPDATE `common_grid_column_template` SET `id`='215', `grid_id`='31', `field`='pEx.subAccount', `header`='Sub Account', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='multiSelect', `placeholder`='Sub Account', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='215');
UPDATE `common_grid_column_template` SET `id`='217', `grid_id`='31', `field`='pEx.approvedEr', `header`='Approved', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Approved Expense Reports', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='217');
UPDATE `common_grid_column_template` SET `id`='218', `grid_id`='31', `field`='pEx.rejectedEr', `header`='Rejected', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Rejected Expense Reports', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='218');
UPDATE `common_grid_column_template` SET `id`='221', `grid_id`='31', `field`='pEx.submittedEr', `header`='Pending', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`=' ', `placeholder`='Pending Expense Reports', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='221');
UPDATE `common_grid_column_template` SET `id`='222', `grid_id`='31', `field`='pEx.totalPayable', `header`='Total Payable', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='right', `search_type`=' ', `placeholder`='Total Payable', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='222');


UPDATE `common_notification_subscription_event` SET `event`='A bill is submitted for your approval' WHERE  `id`=1;
UPDATE `common_notification_subscription_event` SET `event`='A bill you submitted is approved' WHERE  `id`=2;
UPDATE `common_notification_subscription_event` SET `event`='A bill you submitted is rejected' WHERE  `id`=3;
UPDATE `common_notification_subscription_event` SET `event`='A bill is submitted for your approval group' WHERE  `id`=13;
UPDATE `common_notification_subscription_event` SET `event`='There are no users in an assigned approval group' WHERE  `id`=14;
UPDATE `common_notification_subscription_event` SET `event`='A purchase order is submitted for your approval' WHERE  `id`=4;
UPDATE `common_notification_subscription_event` SET `event`='A purchase order you submitted is approved' WHERE  `id`=5;
UPDATE `common_notification_subscription_event` SET `event`='A purchase order you submitted is rejected' WHERE  `id`=6;
UPDATE `common_notification_subscription_event` SET `event`='A purchase order is submitted for your approval group' WHERE  `id`=15;
UPDATE `common_notification_subscription_event` SET `event`='There are no users in an assigned approval group' WHERE  `id`=16;
UPDATE `common_notification_subscription_event` SET `event`='An expense report is submitted for your approval' WHERE  `id`=7;
UPDATE `common_notification_subscription_event` SET `event`='An expense report you submitted is approved' WHERE  `id`=8;
UPDATE `common_notification_subscription_event` SET `event`='An expense report you submitted is rejected' WHERE  `id`=9;
UPDATE `common_notification_subscription_event` SET `event`='An expense report is submitted for your approval group' WHERE  `id`=17;
UPDATE `common_notification_subscription_event` SET `event`='There are no users in an assigned approval group' WHERE  `id`=18;