INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `mobile_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1060, 'Invoices', 'Invoices', 'fa fa-file', '/home/invoices', '0', 'S', 1016, NULL, 'Admin', 8, 'fa fa-file', 'Invoices', 'Invoices', 'A', 0, 1, 0, 0, 'V2', 'INVOICES', 0, '1016', 'System', '2023-04-18 12:42:00', NULL, NULL, NULL, NULL);

INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (143, 'Mark As Paid', 'Mark As Paid', 'MARK_AS_PAID', 'Sytem', '2023-04-18 12:56:42', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (144, 'Mark As Unpaid', 'Mark As Unpaid', 'MARK_AS_UNPAID', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (145, 'Import Invoice', 'Import Invoice', 'IMPORT_INVOICE', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);

INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (536, 1060, 1, 'CREATE_INVOICE', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (537, 1060, 4, 'EDIT_INVOICE', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (538, 1060, 3, 'VIEW_INVOICE_DETAIL_VIEW', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (539, 1060, 5, 'DELETE_INVOICE', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (540, 1060, 10, 'VIEW_INVOICE_AUDIT_TRAIL', 'System', '2023-04-18 13:17:08', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (541, 1060, 39, 'DOWNLOAD_INVOICE_RECEPIT', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (542, 1060, 47, 'EXPORT_INVOICE_CSV', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (543, 1060, 143, 'MARK_AS_INVOICE_PAID', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (544, 1060, 144, 'MARK_AS_INVOICE_UNPAID', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (545, 1060, 145, 'IMPORT_INVOICE', 'System', '2023-04-18 12:45:00', NULL, NULL, NULL, NULL);
