-----hashila---2.8.96------



UPDATE `vendor_grid_column_template` SET `header` = 'Batch ID', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'left', `search_type` = 'input', `placeholder` = 'Batch ID', `column_order` = 1, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.batchId';
UPDATE `vendor_grid_column_template` SET `header` = 'Reference Number', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'left', `search_type` = 'input', `placeholder` = 'Transaction Id', `column_order` = 2, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.txnRef';
UPDATE `vendor_grid_column_template` SET `header` = 'Paid Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Paid Amount', `column_order` = 3, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.paidAmount';
UPDATE `vendor_grid_column_template` SET `header` = 'Transaction Date', `column_show` = 0, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 0, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'center', `search_type` = 'date', `placeholder` = 'Transaction Date', `column_order` = 7, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.txnDate';
UPDATE `vendor_grid_column_template` SET `header` = 'Payment Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'center', `search_type` = 'date', `placeholder` = 'Payment Date', `column_order` = 4, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.paymentDate';
UPDATE `vendor_grid_column_template` SET `header` = 'Approval Status', `column_show` = 0, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 0, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Approval Status', `column_order` = 5, `drop_down_id` = 5, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.approvalStatus';
UPDATE `vendor_grid_column_template` SET `header` = 'Transaction Type', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'left', `search_type` = 'dropdown', `placeholder` = 'Transaction Type', `column_order` = 8, `drop_down_id` = 6, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.paymentType';
UPDATE `vendor_grid_column_template` SET `header` = 'Reason (If failed)', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'left', `search_type` = 'input', `placeholder` = 'Reason (If Faild)', `column_order` = 9, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.reason';
UPDATE `vendor_grid_column_template` SET `header` = 'Payment Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 1, `filter_show` = 1, `is_frozen` = 0, `frozen_direction` = NULL, `align` = 'center', `search_type` = 'input', `placeholder` = 'Payment Status', `column_order` = 6, `drop_down_id` = NULL, `column_width` = 150, `drop_down_url_id` = NULL WHERE `grid_id` = 24 AND `field` = 'txn.paymentStatus';
