----hashila--2.8.305-----


CREATE TABLE vendor_payment_v_card  (
  id int NOT NULL AUTO_INCREMENT,
  tp_id varchar(20) NULL DEFAULT NULL,
  card_type char(1) NULL DEFAULT NULL,
  batch_id int NULL DEFAULT NULL,
  nick_name varchar(200) NULL DEFAULT NULL,
  card_owner varchar(210) NULL DEFAULT NULL,
  amount decimal(19, 2) NOT NULL,
  balance_amount decimal(19, 2) NULL DEFAULT NULL,
  top_up_amount decimal(19, 2) NOT NULL,
  community_vendor_id int NULL DEFAULT NULL,
  user_name varchar(100) NULL DEFAULT NULL,
  status char(1) NOT NULL,
  sync_status char(1) NOT NULL,
  expire_on datetime(0) NULL DEFAULT NULL,
  credentials varchar(100) NULL DEFAULT NULL,
  created_by varchar(100) NOT NULL,
  created_on datetime(0) NOT NULL,
  created_by_name varchar(200) NULL DEFAULT NULL,
  update_by varchar(100) NULL DEFAULT NULL,
  update_on datetime(0) NULL DEFAULT NULL,
  delete_by varchar(100) NULL DEFAULT NULL,
  delete_on datetime(0) NULL DEFAULT NULL,
  cancellable_date datetime(0) NULL DEFAULT NULL,
  scheduled_date datetime(0) NULL DEFAULT NULL,
  scheduled_time varchar(5) NULL DEFAULT NULL,
  effective_until date NULL DEFAULT NULL,
  precise_pay tinyint NOT NULL,
  ref_no varchar(16) NULL DEFAULT NULL,
  redeemed_amount decimal(19, 2) NULL DEFAULT NULL,
  card_number varchar(100) NULL DEFAULT NULL,
  cancel_reason varchar(255) NULL DEFAULT NULL,
  payee_type char(1) NULL DEFAULT NULL,
  contact_number varchar(20) NULL DEFAULT NULL,
  first_name varchar(100) NULL DEFAULT NULL,
  last_name varchar(100) NULL DEFAULT NULL,
  customer_id varchar(100) NULL DEFAULT NULL,
  po_id int NULL DEFAULT NULL,
  v_card_id int NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
