---------------Hashila-----2.1.119--------

INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 'Payments', 'Payments', 'fa fa-credit-card', '/home/payments', '0', 'S', 1015, NULL, 'Admin', 13, 'fa fa-credit-card', 'Payments', 'Payments', 'A', 0, 1, 0, 'V2', 'PAYMENTS', 1, '1005,1015', 'System', '2021-09-06 05:48:40', NULL, NULL, NULL, NULL);


INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (93, 'Pay Now', 'Pay Now', 'PAY_NOW', 'System', '2021-09-02 09:43:40', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (94, 'Make an Offline Payment', 'Make an Offline Payment', 'MAKE_AN_OFFLINE_PAYMENT', 'System', '2021-09-02 09:44:21', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (95, 'Schedule Payment', 'Schedule Payment', 'SCHEDULE_PAYMENT', 'System', '2021-09-02 09:45:47', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (96, 'Cancel Batch Payment', 'Cancel Batch Payment', 'CANCEL_BATCH_PAYMENT', 'System', '2021-09-02 09:46:42', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (98, 'Download Attachment', 'Download Attachment', 'DOWNLOAD_ATTACHMENT', 'Syastem', '2021-09-13 11:02:03', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (101, 'View Summary', 'View Summary', 'VIEW_SUMMARY', 'System', '2021-09-13 14:30:38', NULL, NULL, NULL, NULL);


INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 1, 'PAYMENT_CREATE', 'System', '2021-08-18 15:05:52', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 3, 'PAYMENT_DETAIL_VIEW', 'System', '2021-09-02 10:53:27', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 6, 'PAYMENT_APPROVE', 'System', '2021-09-02 10:53:52', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 7, 'PAYMENT_REJECT', 'System', '2021-09-02 10:54:15', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 11, 'PAYMENT_SUBMIT', 'System', '2021-09-02 10:54:48', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 93, 'PAYMENT_PAY_NOW', 'System', '2021-09-02 10:55:40', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 94, 'PAYMENT_MAKE_AN_OFFLINE_PAYMENT', 'System', '2021-09-02 11:00:33', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 95, 'PAYMENT_SCHEDULE_PAYMENT', 'System', '2021-09-02 11:00:58', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 96, 'PAYMENT_CANCEL_BATCH_PAYMENT', 'System', '2021-09-02 11:01:31', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 40, 'PAYMENT_OVERRIDE_APPROVAL', 'System', '2021-09-02 11:27:38', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 98, 'PAYMENT_DOWNLOAD_ATTACHMENT', 'System', '2021-09-13 11:36:11', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 101, 'PAYMENT_VIEW_SUMMARY', 'System', '2021-09-13 14:32:12', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1029, 10, 'PAYMENT_VIEW_AUDIT_TRIAL', 'System', '2021-09-13 14:27:21', NULL, NULL, NULL, NULL);
