--------------Indra------2.1.97------------

INSERT INTO `umm_user_mst` (`uuid`, `role_id`, `user_name`, `name`, `address`, `email`, `telephone_no`, `status`, `login_attempt`, `password`, `created_on`, `created_by`, `nic_passport_no`, `image_attached`, `first_login`, `account_locked_date`, `pro_pic_content_type`, `pro_pic_name`, `update_on`, `update_by`, `last_login_date`, `last_login_date_time`, `user_type`, `temporary_password`, `temporary_password_status`, `temporary_password_issue_date`, `temporary_password_expired_date`, `workflow_id`, `propic_id`, `delete_by`, `delete_on`) VALUES ('4ccc7194-5df8-4544-b394-3e62d62acdf0', 1, 'papertrl_admin', 'admin', NULL, 'papertrl_admin', NULL, 'L', 0, '$2a$10$y7uaBNBgCUO479OdpBhd0uKt4hT1KCavYFpAnczN4/NCoDmN5t7Y.', '2021-09-09 11:12:37', 'PAPERTRL_admin', NULL, 'N', 'N', NULL, NULL, NULL, NULL, '', NULL, '2021-09-09 03:57:09', 'I', '', 'A', '2021-09-09 00:00:00', '2021-09-09 00:00:00', NULL, NULL, NULL, NULL);

INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1030, 'Bill Templates', 'Bill Templates', 'fa fa-file-image-o', '/home/bills', '3', 'S', 1005, NULL, 'Admin', 2, 'fa fa-file-image-o', 'Bill Templates', 'Bill Templates', 'A', 0, 1, 0, 'V2', 'BILL_TEMPLATES', 0, '1005,1015', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);

INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (97, 'Download attachments', 'Download Attachments', 'DOWNLOAD_ATTACHMENTS', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);

INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (410, 1030, 1, 'BILL_TEMPLATES_CREATE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (411, 1030, 4, 'BILL_TEMPLATES_EDIT', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (412, 1030, 14, 'BILL_TEMPLATES_ACTIVATE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (413, 1030, 13, 'BILL_TEMPLATES_INACTIVATE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (414, 1030, 5, 'BILL_TEMPLATES_DELETE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (415, 1030, 3, 'BILL_TEMPLATES_DETAIL_VIEW', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (416, 1030, 97, 'BILL_TEMPLATES_DOWNLOAD', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);


INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1031, 'Recurring Bills', 'Recurring Bills', 'fa fa-retweet', '/home/bills', '4', 'S', 1005, NULL, 'Admin', 2, 'fa fa-retweet', 'Recurring Bills', 'Recurring Bills', 'A', 0, 1, 0, 'V2', 'RECURRING_BILLS', 0, '1005,1015', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);


INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (417, 1031, 1, 'RECURRING_BILLS_CREATE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (418, 1031, 4, 'RECURRING_BILLS_EDIT', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (419, 1031, 14, 'RECURRING_BILLS_ACTIVATE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (420, 1031, 13, 'RECURRING_BILLS_INACTIVATE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (421, 1031, 5, 'RECURRING_BILLS_DELETE', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (422, 1031, 3, 'RECURRING_BILLS_DETAIL_VIEW', 'admin', '2021-09-09 11:59:00', NULL, NULL, NULL, NULL);

