-----Danuddara- 0.0.5---



ALTER TABLE `payment_transaction` 
DROP COLUMN `batch_id`,
DROP COLUMN `batch_no`,
DROP COLUMN `is_online`,
DROP COLUMN `document_type`,
DROP COLUMN `document_id`,
DROP COLUMN `document_no`,
DROP COLUMN `offline_payment_id`,
DROP COLUMN `vendor_id`,
DROP COLUMN `employee_id`,
DROP COLUMN `bill_id`,
DROP COLUMN `bill_no`,
DROP COLUMN `txn_type_name`,
DROP COLUMN `txn_discount`,
DROP COLUMN `txn_date`,
DROP COLUMN `status`,
DROP COLUMN `payment_status`,
DROP COLUMN `reason`,
DROP COLUMN `bank_account_id`,
DROP COLUMN `created_by`,
DROP COLUMN `created_on`,
DROP COLUMN `created_by_name`,
DROP COLUMN `update_by`,
DROP COLUMN `update_on`,
DROP COLUMN `delete_by`,
DROP COLUMN `delete_on`,
DROP COLUMN `approval_user`,
DROP COLUMN `approval_group_name`,
DROP COLUMN `approval_group`,
DROP COLUMN `approval_user_name`,
DROP COLUMN `workflow_id`,
DROP COLUMN `workflow_level`,
DROP COLUMN `no_of_levels`,
DROP COLUMN `approved_date`,
DROP COLUMN `remarks`,
DROP COLUMN `cancelled_by`,
DROP COLUMN `cancelled_on`,
DROP COLUMN `cancellable_date`,
DROP COLUMN `export_status`,
DROP COLUMN `automation_id`,
DROP COLUMN `automation_rule_id`,
DROP COLUMN `scheduled_date`,
DROP COLUMN `scheduled_time`,
CHANGE COLUMN `tp_txn_id` `tp_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `comment`,
MODIFY COLUMN `comment` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `txn_amount`,
ADD COLUMN `correlation_id` varchar(300) NULL AFTER `payment_date`,
ADD COLUMN `idempotency_key` varchar(300) NULL AFTER `correlation_id`,
ADD COLUMN `credentials` varchar(100) NULL AFTER `idempotency_key`,
ADD COLUMN `attempt` int NULL AFTER `credentials`,
ADD COLUMN `tenant_id` varchar(100) NULL AFTER `attempt`,
ADD COLUMN `osn` varchar(50) NULL AFTER `tenant_id`,
ADD COLUMN `client_id` varchar(100) NULL AFTER `osn`,
ADD COLUMN `company_name` varchar(255) NULL AFTER `client_id`,
ADD COLUMN `check_number` varchar(100) NULL AFTER `company_name`,
ADD COLUMN `top_up_amount` decimal(19, 2) NULL AFTER `check_number`,
ADD COLUMN `expire_on` datetime(6) NULL AFTER `top_up_amount`,
ADD COLUMN `created_on` datetime(6) NULL AFTER `expire_on`,
ADD COLUMN `recipient_data_id` int NULL AFTER `created_on`,
ADD COLUMN `client_config_id` int NULL AFTER `recipient_data_id`;


ALTER TABLE `audit_log` 
MODIFY COLUMN `transaction_id` int NULL AFTER `tenant_id`,
ADD COLUMN `tp_txn_id` varchar(100) NULL AFTER `created_on`;