INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (44, NULL, 'ADMIRAL CONSULTING GROUP', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ADMIRAL CONSULTING GROUP', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (45, NULL, 'ANSON COUNTY TAX DEPARTMENT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ANSON COUNTY TAX DEPARTMENT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (46, NULL, 'AQUESTA BANK', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'AQUESTA BANK', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (47, NULL, 'AQUA FILTER FRESH, INC. TYLER MOUNTAIN WATER CO.', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'AQUA FILTER FRESH, INC. TYLER MOUNTAIN WATER CO.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (48, NULL, 'ARARAT ROCK PRODUCTS', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ARARAT ROCK PRODUCTS', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (49, NULL, 'AVERY COUNTY TAX OFFICE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'AVERY COUNTY TAX OFFICE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (50, NULL, 'AMERICAN WIND ENERGY ASSOCIATION', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'AMERICAN WIND ENERGY ASSOCIATION', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (51, NULL, 'AXIS ENERGY', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'AXIS ENERGY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (52, NULL, 'DUANE BARRETT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DUANE BARRETT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (53, NULL, 'BEAUFORT COUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'BEAUFORT COUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (54, NULL, 'BEDFORD REGIONAL WATER AUTHORITY', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'BEDFORD REGIONAL WATER AUTHORITY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (55, NULL, 'DHAVAL BHALODIA', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DHAVAL BHALODIA', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (56, NULL, 'MICHAEL BISSONNETTE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'MICHAEL BISSONNETTE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (57, NULL, 'CAPITOL SERVICES', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CAPITOL SERVICES', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (58, NULL, 'CHORUS CALL, INC.', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CHORUS CALL, INC.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (59, NULL, 'CITY OF MOUNT AIRY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CITY OF MOUNT AIRY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (60, NULL, 'COGENCY GLOBAL', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'COGENCY GLOBAL', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (61, NULL, 'COMCAST', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'COMCAST', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (62, NULL, 'CORE ENERGY WORKS LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CORE ENERGY WORKS LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (63, NULL, 'CSC- CORPORATION SERVICE COMPANY', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CSC- CORPORATION SERVICE COMPANY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (64, NULL, 'CT CORPORATION', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CT CORPORATION', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (65, NULL, 'DELUXE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DELUXE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (66, NULL, 'DIXON HUGHES GOODMAN LLP', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DIXON HUGHES GOODMAN LLP', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (67, NULL, 'DOMINION NORTH CAROLINA', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DOMINION NORTH CAROLINA', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (68, NULL, 'DUKE ENERGY ', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DUKE ENERGY ', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (69, NULL, 'DUKE ENERGY PROGRESS  ', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DUKE ENERGY PROGRESS  ', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (70, NULL, 'DUKE ENERGY {UTILITY}', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DUKE ENERGY {UTILITY}', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (71, NULL, 'DUKE ENERGY {WELL}', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DUKE ENERGY {WELL}', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (72, NULL, 'DUKE ENERGY PROGRESS {V}', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DUKE ENERGY PROGRESS {V}', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (73, NULL, 'EDGECOMBE COUNTY EMC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'EDGECOMBE COUNTY EMC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (74, NULL, 'EDGECOMBE COUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'EDGECOMBE COUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (75, NULL, 'EIC MASTER TENANT, LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'EIC MASTER TENANT, LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (76, NULL, 'EMD INTERNATIONAL', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'EMD INTERNATIONAL', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (77, NULL, 'ENERGY ACUITY, LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ENERGY ACUITY, LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (78, NULL, 'FIFTH THIRD BANK', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'FIFTH THIRD BANK', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (79, NULL, 'FIRSTAR DEVELOPMENT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'FIRSTAR DEVELOPMENT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (80, NULL, 'FRANKLIN COUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'FRANKLIN COUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (81, NULL, 'FULTON TECHNOLOGY', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'FULTON TECHNOLOGY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (82, NULL, 'GATES COUNTY TAX ADMINISTRATOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'GATES COUNTY TAX ADMINISTRATOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (83, NULL, 'JOE GLINKSI', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'JOE GLINKSI', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (84, NULL, 'ANDREW L. GOLEMBESKI', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ANDREW L. GOLEMBESKI', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (85, NULL, 'GREENBYTE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'GREENBYTE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (86, NULL, 'GRIDFORCE ENERGY MANAGEMENT LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'GRIDFORCE ENERGY MANAGEMENT LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (87, NULL, 'HARTFORD INSURANCE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'HARTFORD INSURANCE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (88, NULL, 'EMANUEL B HUDOCK, CPA', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'EMANUEL B HUDOCK, CPA', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (89, NULL, 'HUNTON ANDREWS KURTH, LLP', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'HUNTON ANDREWS KURTH, LLP', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (90, NULL, 'JUSTIFACTS CREDENTIAL VERIFICATION, INC.', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'JUSTIFACTS CREDENTIAL VERIFICATION, INC.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (91, NULL, 'KRAYN WIND LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'KRAYN WIND LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (92, NULL, 'JOYCE LAND LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'JOYCE LAND LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (93, NULL, 'LEECH TISHMAN FUSCALDO & LAMPL, LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'LEECH TISHMAN FUSCALDO & LAMPL, LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (94, NULL, 'SPUS8 LIBERTY CENTER LP', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SPUS8 LIBERTY CENTER LP', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (95, NULL, 'LISTEN HEAR HOME ENTERTAINMENT & AUTOMATION', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'LISTEN HEAR HOME ENTERTAINMENT & AUTOMATION', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (96, NULL, 'JOHN R MARKWELL', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'JOHN R MARKWELL', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (97, NULL, 'KARALYN MATHESON', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'KARALYN MATHESON', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (98, NULL, 'NICOLAS MATOS', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'NICOLAS MATOS', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (99, NULL, 'JEREMY MERICH', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'JEREMY MERICH', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (100, NULL, 'OLIVIA MERICH', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'OLIVIA MERICH', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (101, NULL, 'LEIGH MIHALICH', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'LEIGH MIHALICH', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (102, NULL, 'MONTGOMERY COUNTY TAX', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'MONTGOMERY COUNTY TAX', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (103, NULL, 'NASH CCOUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'NASH CCOUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (104, NULL, 'NATIONWIDE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'NATIONWIDE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (105, NULL, 'NC DOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'NC DOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (106, NULL, 'NC SECRETARY OF STATE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'NC SECRETARY OF STATE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (107, NULL, 'REBECCA G. NEWMAN', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'REBECCA G. NEWMAN', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (108, NULL, 'O2 DEVELOPMENT SERVICES LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'O2 DEVELOPMENT SERVICES LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (109, NULL, 'OFFICE FURNITURE HEAVEN', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'OFFICE FURNITURE HEAVEN', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (110, NULL, 'Oppidum Renewables USA Inc.', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'Oppidum Renewables USA Inc.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (111, NULL, 'PETRA ENGINEERING, PLLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'PETRA ENGINEERING, PLLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (112, NULL, 'PJM ENVIRONMENTAL INFORMATION SERVICES', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'PJM ENVIRONMENTAL INFORMATION SERVICES', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (113, NULL, 'RBI SOLAR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'RBI SOLAR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (114, NULL, 'RED STONE RENEWABLE ENERGY', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'RED STONE RENEWABLE ENERGY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (115, NULL, 'ROBESON COUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ROBESON COUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (116, NULL, 'ROBESON COUNTY WATER DEPARTMENT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ROBESON COUNTY WATER DEPARTMENT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (117, NULL, 'THE ROVISYS COMPANY', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'THE ROVISYS COMPANY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (118, NULL, 'ROWAN COUNTY TAX ADMINISTRATION', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ROWAN COUNTY TAX ADMINISTRATION', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (119, NULL, 'CHRIS RUGH', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'CHRIS RUGH', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (120, NULL, 'KRISHNA SANTHANAM', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'KRISHNA SANTHANAM', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (121, NULL, 'SEI ENGINEERING', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SEI ENGINEERING', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (122, NULL, 'SOLAR ENERGY INDUSTRIES ASSOCIATION (SEIA)', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SOLAR ENERGY INDUSTRIES ASSOCIATION (SEIA)', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (123, NULL, 'SFLAND LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SFLAND LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (124, NULL, 'SHANNON CONSTRUCTION', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SHANNON CONSTRUCTION', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (125, NULL, 'SOLAR OPERATIONS SOLUTIONS LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SOLAR OPERATIONS SOLUTIONS LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (126, NULL, 'SOLAR DEVELOPMENT SERVICES, LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SOLAR DEVELOPMENT SERVICES, LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (127, NULL, 'SPECIAL COUNSEL, INC.', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SPECIAL COUNSEL, INC.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (128, NULL, 'JIM SPENCER', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'JIM SPENCER', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (129, NULL, 'STATE CORPORATION COMMISSION', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'STATE CORPORATION COMMISSION', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (130, NULL, 'STATE OF DELAWARE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'STATE OF DELAWARE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (131, NULL, 'STCE EMC LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'STCE EMC LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (132, NULL, 'SUN RAISED FARMS, LLC', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SUN RAISED FARMS, LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (133, NULL, 'SURREY BANK & TRUST', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SURREY BANK & TRUST', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (134, NULL, 'SURREY COUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'SURREY COUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (135, NULL, 'TOLSON LLC ', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'TOLSON LLC ', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (136, NULL, 'TOSHIBA FINANCIAL SERVICES', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'TOSHIBA FINANCIAL SERVICES', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (137, NULL, 'TOWN OF BEDFORD', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'TOWN OF BEDFORD', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (138, NULL, 'TOWN OF WADESBORO', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'TOWN OF WADESBORO', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (139, NULL, 'TRAVELERS INSURANCE', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'TRAVELERS INSURANCE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (140, NULL, 'TUCKER ARENSBERG, P.C.', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'TUCKER ARENSBERG, P.C.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (141, NULL, 'USDA/RURAL DEVELOPMENT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'USDA/RURAL DEVELOPMENT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (142, NULL, 'VERIZON', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'VERIZON', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (143, NULL, 'ROBERT JUDE WARNER', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ROBERT JUDE WARNER', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (144, NULL, 'LINDA WEANT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'LINDA WEANT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (145, NULL, 'MARGARET WEANT', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'MARGARET WEANT', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (146, NULL, 'ERIK WIDNER', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'ERIK WIDNER', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (147, NULL, 'DAVID A WILLIAMS SR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'DAVID A WILLIAMS SR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (148, NULL, 'YADKIN COUNTY TAX COLLECTOR', NULL, NULL, NULL, '2020-06-09 16:52:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'YADKIN COUNTY TAX COLLECTOR', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-09 16:52:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (149, NULL, 'CUMMINGS WESTLAKE LLC', NULL, NULL, NULL,'2020-06-25 13:05:25', 'admin', NULL, NULL, NULL, NULL, NULL, 'CUMMINGS WESTLAKE LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-25 13:05:25', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (150, NULL, 'MP2 ENERGY TEXAS LLC', NULL, NULL, NULL,'2020-06-30 13:27:32', 'admin', NULL, NULL, NULL, NULL, NULL, 'MP2 ENERGY TEXAS LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-06-30 13:27:32', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (151, NULL, 'NORTON ROSE FULBRIGHT US LLP', NULL, NULL, NULL,'2020-07-01 19:49:18', 'admin', NULL, NULL, NULL, NULL, NULL, 'NORTON ROSE FULBRIGHT US LLP', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 19:49:18', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (152, NULL, 'SEB', NULL, NULL, NULL,'2020-07-01 19:49:33', 'admin', NULL, NULL, NULL, NULL, NULL, 'SEB', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 19:49:33', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (153, NULL, 'BLUE POWER PARTNERS A/S', NULL, NULL, NULL,'2020-07-01 19:49:48', 'admin', NULL, NULL, NULL, NULL, NULL, 'BLUE POWER PARTNERS A/S', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 19:49:48', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (154, NULL, 'BLACK & MCDONALD POWER UTILITY', NULL, NULL, NULL,'2020-07-01 19:50:15', 'admin', NULL, NULL, NULL, NULL, NULL, 'BLACK & MCDONALD POWER UTILITY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 19:50:15', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (155, NULL, 'VESTAS-AMERICAN WIND TECHNOLOGY, INC.', NULL, NULL, NULL,'2020-07-01 19:50:33', 'admin', NULL, NULL, NULL, NULL, NULL, 'VESTAS-AMERICAN WIND TECHNOLOGY, INC.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 19:50:33', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (156, NULL, 'BEARKAT RENEWABLE ENERGY PROJECT, LLC', NULL, NULL, NULL,'2020-07-01 20:32:58', 'admin', NULL, NULL, NULL, NULL, NULL, 'BEARKAT RENEWABLE ENERGY PROJECT, LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 20:32:58', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (157, NULL, 'TENASKA POWER SERVICES CO.', NULL, NULL, NULL,'2020-07-01 20:33:21', 'admin', NULL, NULL, NULL, NULL, NULL, 'TENASKA POWER SERVICES CO.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 20:33:21', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (158, NULL, 'TRI GLOBAL ENERGY LLC', NULL, NULL, NULL,'2020-07-01 20:33:56', 'admin', NULL, NULL, NULL, NULL, NULL, 'TRI GLOBAL ENERGY LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 20:33:56', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (159, NULL, 'OPERATIONAL RISK INTELLIGENCE', NULL, NULL, NULL,'2020-07-01 20:34:15', 'admin', NULL, NULL, NULL, NULL, NULL, 'OPERATIONAL RISK INTELLIGENCE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 20:34:15', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (160, NULL, 'HUSCH BLACKWELL', NULL, NULL, NULL,'2020-07-01 20:34:42', 'admin', NULL, NULL, NULL, NULL, NULL, 'HUSCH BLACKWELL', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-01 20:34:42', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (161, NULL, 'PROJECTUM', NULL, NULL, NULL,'2020-07-14 20:31:31', 'admin', NULL, NULL, NULL, NULL, NULL, 'PROJECTUM', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-14 20:32:36', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (162, NULL, 'SIDLEY AUSTIN LLP', NULL, NULL, NULL,'2020-07-14 20:32:08', 'admin', NULL, NULL, NULL, NULL, NULL, 'SIDLEY AUSTIN LLP', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-14 20:32:08', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (163, NULL, 'BRUUN & HJEJLE', NULL, NULL, NULL,'2020-07-14 20:33:23', 'admin', NULL, NULL, NULL, NULL, NULL, 'BRUUN & HJEJLE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-14 20:33:23', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (164, NULL, 'ROSE & KIERNAN, INC.', NULL, NULL, NULL,'2020-07-28 14:19:18', 'admin', NULL, NULL, NULL, NULL, NULL, 'ROSE & KIERNAN, INC.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-28 14:19:18', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (165, NULL, 'AON RISK SERVICES NORTHEAST, INC.', NULL, NULL, NULL,'2020-07-28 14:19:39', 'admin', NULL, NULL, NULL, NULL, NULL, 'AON RISK SERVICES NORTHEAST, INC.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-07-28 14:19:39', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (166, NULL, 'DNV GL ENERGY', NULL, NULL, NULL,'2020-08-10 17:48:02', 'admin', NULL, NULL, NULL, NULL, NULL, 'DNV GL ENERGY', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-10 17:48:02', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (167, NULL, 'Energy Consultants Project Management LLC', NULL, NULL, NULL,'2020-08-10 17:56:46', 'admin', NULL, NULL, NULL, NULL, NULL, 'Energy Consultants Project Management LLC', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-10 17:56:46', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (168, NULL, 'EXUS NORTH AMERICA MANAGEMENT PARTNERS', NULL, NULL, NULL,'2020-08-12 14:03:37', 'admin', NULL, NULL, NULL, NULL, NULL, 'EXUS NORTH AMERICA MANAGEMENT PARTNERS', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-12 14:03:37', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (169, NULL, 'WESTWOOD PROFESSIONAL SERVICES', NULL, NULL, NULL,'2020-08-18 15:34:48', 'admin', NULL, NULL, NULL, NULL, NULL, 'WESTWOOD PROFESSIONAL SERVICES', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-18 15:34:48', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (170, NULL, 'WESTSLOPE CONSULTING', NULL, NULL, NULL,'2020-08-18 15:38:10', 'admin', NULL, NULL, NULL, NULL, NULL, 'WESTSLOPE CONSULTING', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-18 15:38:10', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (171, NULL, 'United Salvage Associates, Inc.', NULL, NULL, NULL,'2020-08-21 14:33:15', 'admin', NULL, NULL, NULL, NULL, NULL, 'United Salvage Associates, Inc.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-21 14:33:15', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (172, NULL, 'Anemometry Specialists, Inc.', NULL, NULL, NULL,'2020-08-25 16:04:34', 'admin', NULL, NULL, NULL, NULL, NULL, 'Anemometry Specialists, Inc.', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-25 16:04:34', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (173, NULL, 'Wireless Innovation', NULL, NULL, NULL,'2020-08-25 16:05:31', 'admin', NULL, NULL, NULL, NULL, NULL, 'Wireless Innovation', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-25 16:05:31', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (174, NULL, 'VOLT ELECTRICITY PROVIDER', NULL, NULL, NULL,'2020-08-25 17:36:07', 'admin', NULL, NULL, NULL, NULL, NULL, 'VOLT ELECTRICITY PROVIDER', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-25 17:36:07', 'admin');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (175, NULL, 'WESTEX TELEPHONE COOPERATIVE', NULL, NULL, NULL,'2020-08-25 19:53:03', 'ExusAP', NULL, NULL, NULL, NULL, NULL, 'WESTEX TELEPHONE COOPERATIVE', NULL, NULL, NULL, NULL, 'A', 'N', '2020-08-25 19:53:03', 'ExusAP');
INSERT INTO `vp_vendor_mst` (`id`, `user_id`, `business_name`, `cc_email`, `contact_number`, `contact_person`, `date_created`, `created_by`, `email`, `emp_id_no`, `exempt_payee_code`, `fatca_reporting_code`, `fax`, `name`, `social_sec_no`, `tax_class_otherdetail`, `tax_classification`, `tax_code`, `status`, `sync_status`, `last_updated_on`, `last_updated_by`) VALUES (176, NULL, 'WESTERN LAND SERVICES', NULL, NULL, NULL,'2020-09-09 20:04:35', 'admin', NULL, NULL, NULL, NULL, NULL, 'WESTERN LAND SERVICES', NULL, NULL, NULL, NULL, 'A', 'N', '2020-09-09 20:04:35', 'admin');




/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40000 ALTER TABLE `vp_vendor_address` DISABLE KEYS */;
INSERT INTO `vp_vendor_address` (`address_line_1`, `address_line_2`, `city_other`, `state_other`, `type`, `zipcode_other`, `city`, `country`, `state`, `vendor_mst_id`, `vendor_temp_id`, `zipcode`) VALUES
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 44, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 45, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 46, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 47, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 48, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 49, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 50, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 51, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 52, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 53, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 54, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 55, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 56, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 57, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 58, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 59, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 60, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 61, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 62, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 63, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 64, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 65, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 66, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 67, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 68, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 69, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 70, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 71, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 72, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 73, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 74, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 75, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 76, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 77, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 78, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 79, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 80, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 81, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 82, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 83, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 84, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 85, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 86, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 87, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 88, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 89, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 90, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 91, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 92, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 93, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 94, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 95, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 96, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 97, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 98, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 99, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 100, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 101, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 102, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 103, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 104, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 105, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 106, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 107, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 108, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 109, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 110, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 111, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 112, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 113, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 114, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 115, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 116, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 117, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 118, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 119, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 120, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 121, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 122, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 123, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 124, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 125, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 126, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 127, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 128, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 129, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 130, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 131, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 132, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 133, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 134, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 135, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 136, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 137, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 138, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 139, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 140, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 141, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 142, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 143, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 144, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 145, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 146, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 147, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 148, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 149, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 150, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 151, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 152, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 153, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 154, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 155, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 156, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 157, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 158, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 159, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 160, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 161, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 162, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 163, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 164, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 165, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 166, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 167, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 168, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 169, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 170, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 171, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 172, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 173, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 174, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 175, NULL, NULL),
	(NULL, NULL, NULL, NULL, 'PA', NULL, NULL, NULL, NULL, 176, NULL, NULL);
/*!40000 ALTER TABLE `vp_vendor_address` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

