UPDATE `vendor_grid_column_template` SET `id`='253', `grid_id`='9', `field`='vi.tenantId', `header`='Customer', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='multiSelect', `placeholder`='Customer', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='253');
UPDATE `vendor_grid_column_template` SET `id`='254', `grid_id`='9', `field`='chk.paymentReferanceNo', `header`='Payment Ref', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Payment Ref', `column_order`='4', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='254');
UPDATE `vendor_grid_column_template` SET `id`='255', `grid_id`='9', `field`='chk.amount', `header`='Amount', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='right', `search_type`='numeric', `placeholder`='Amount', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='255');
UPDATE `vendor_grid_column_template` SET `id`='256', `grid_id`='9', `field`='chk.discountAmount', `header`='Discount', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='right', `search_type`='numeric', `placeholder`='Discount', `column_order`='19', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='256');
UPDATE `vendor_grid_column_template` SET `id`='257', `grid_id`='9', `field`='chk.paymentDate', `header`='Date', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='center', `search_type`='date', `placeholder`='Date', `column_order`='5', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='257');
UPDATE `vendor_grid_column_template` SET `id`='258', `grid_id`='9', `field`='vi.invoiceNo', `header`='Invoice Number', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Invoice Number', `column_order`='4', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='258');
UPDATE `vendor_grid_column_template` SET `id`='259', `grid_id`='9', `field`='action', `header`='Action', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='actionButton', `placeholder`='', `column_order`='2', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='259');


UPDATE `vendor_grid_column_template` SET `grid_id` = 4, `field` = 'po.tenantId', `header` = 'Customer Name', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'multiSelect', `placeholder` = 'All', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 201;
UPDATE `vendor_grid_column_template` SET `grid_id` = 7, `field` = 'vi.tenantId', `header` = 'Customer Name', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'multiSelect', `placeholder` = 'All', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 239;


DELETE FROM `vendor_grid_state_user_wice`;
DELETE FROM `vendor_grid_column_user_wice`;