---------Amal---------2.2.98---------

INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1035, 'Vendors', 'Vendors', 'pi pi-users', '/home/vendor', '0', 'S', 1004, NULL, 'Admin', 8, 'pi pi-users', 'Vendors', 'Vendors', 'A', 0, 1, 0, 'V2', 'VENDORS_SUB', 0, '1004,1015', 'System', '2021-10-29 11:37:17', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1037, 'Send An Invitation', 'Send An Invitation', 'fa fa-envelope-open', '/home/vendor', '2', 'S', 1004, NULL, 'Admin', 8, 'fa fa-envelope-open', 'Send An Invitation', 'Send An Invitation', 'A', 0, 1, 0, 'V2', 'SEND_AN_INVITATION', 0, '1004,1015', 'System', '2021-10-29 11:43:12', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1038, 'Import Vendors', 'Import Vendors', 'fa fa-sign-in', '/home/vendor', '3', 'S', 1004, NULL, 'Admin', 8, 'fa fa-sign-in', 'Import Vendors', 'Import Vendors', 'A', 0, 1, 0, 'V2', 'IMPORT_VENDORS', 0, '1004,1015', 'System', '2021-10-29 12:40:39', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1039, 'Vendor Request', 'Vendor Request', 'fa fa-paper-plane', '/home/vendor', '4', 'S', 1004, NULL, 'Admin', 8, 'fa fa-paper-plane', 'Vendor Request', 'Vendor Request', 'A', 0, 1, 0, 'V2', 'VENDOR_REQUEST', 0, '1004,1015', 'System', '2021-10-29 12:38:15', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1040, 'Community Vendors', 'Community Vendors', 'fa fa-users', '/home/vendor', '5', 'S', 1004, NULL, 'Admin', 8, 'fa fa-users', 'Community Vendors', 'Community Vendors', 'A', 0, 1, 0, 'V2', 'COMMUNITY_VENDORS', 0, '1004,1015', 'System', '2021-10-29 13:24:22', NULL, NULL, NULL, NULL);

UPDATE `umm_menu_privilage` SET `menu_id`='1035' WHERE  `id`=55;
UPDATE `umm_menu_privilage` SET `menu_id`='1037' WHERE  `id`=56;
UPDATE `umm_menu_privilage` SET `menu_id`='1038' WHERE  `id`=57;
UPDATE `umm_menu_privilage` SET `menu_id`='1039' WHERE  `id`=58;
UPDATE `umm_menu_privilage` SET `menu_id` = '1035' WHERE `id` = 59;
UPDATE `umm_menu_privilage` SET `menu_id` = '1035' WHERE `id` = 60;
UPDATE `umm_menu_privilage` SET `menu_id` = '1040' WHERE `id` = 375;
UPDATE `umm_menu_privilage` SET `menu_id` = '1035' WHERE `id` = 384;
UPDATE `umm_menu_privilage` SET `menu_id` = '1037' WHERE `id` = 385;
UPDATE `umm_menu_privilage` SET `menu_id` = '1037' WHERE `id` = 386;
UPDATE `umm_menu_privilage` SET `menu_id` = '1039' WHERE `id` = 387;
UPDATE `umm_menu_privilage` SET `menu_id` = '1039' WHERE `id` = 388;

INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (102, 'Show Bills', 'Show bills', 'SHOW_BILLS', 'System', '2021-10-29 08:06:45', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (103, 'Show Bill Payments', 'Show Bill Payments', 'SHOW_BILL_PAYMENTS', 'System', '2021-10-29 08:12:51', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (104, 'Show Purchase Orders', 'Show Purchase Orders', 'SHOW_PURCHASE_ORDERS', 'System', '2021-10-29 08:17:05', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (105, 'Show PO Receipts', 'Show PO Receipts', 'SHOW_PO_RECEIPTS', 'System', '2021-10-29 08:22:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (106, 'Create And Send Invitation', 'Create And Send Invitation', 'CREATE_AND_SEND_INVITATION', 'System', '2021-10-29 08:36:33', NULL, NULL, NULL, NULL);
INSERT INTO `umm_privilages` (`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (107, 'Upload And Send Invitation', 'Upload And Send Invitation', 'UPLOAD_AND_SEND_INVITATION', 'System', '2021-10-29 08:40:49', NULL, NULL, NULL, NULL);

INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (428, 1035, 102, 'VENDOR_SHOW_BILLS', 'System', '2021-10-29 08:09:09', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (429, 1035, 103, 'VENDOR_SHOW_BILL_PAYMENTS', 'System', '2021-10-29 08:15:01', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (430, 1035, 104, 'VENDOR_SHOW_PURCHASE_ORDERS', 'System', '2021-10-29 08:19:07', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (431, 1035, 105, 'VENDOR_SHOW_PO_RECEIPTS', 'System', '2021-10-29 08:23:32', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (432, 1035, 13, 'VENDOR_INACTIVATE', 'System', '2021-10-29 08:33:58', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (436, 1040, 3, 'VENDOR_COMMUNITY_VENDORS_DETAIL_VIEW', 'System', '2021-10-29 08:48:38', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage` (`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (437, 1035, 14, 'VENDOR_ACTIVATE', 'System', '2021-11-01 14:08:03', NULL, NULL, NULL, NULL);
