---------Hashila--------2.6.52-----------

UPDATE `common_grid_column_template` SET `grid_id` = 50, `field` = 'statement.totalRecords', `header` = 'Total Records', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'number', `placeholder` = 'Total Records', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 510;
UPDATE `common_grid_column_template` SET `grid_id` = 50, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 511;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 512;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'card.cardNo', `header` = 'Card Number', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Card Number', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 513;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'card.employeeId', `header` = 'Employee', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'dropdown', `placeholder` = 'Employee', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 514;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'card.createdBy', `header` = 'Created By', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Created By', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 515;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'card.createdOn', `header` = 'Created Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Created Date', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 516;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'card.status', `header` = 'Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Status', `column_order` = 7, `drop_down_id` = 1, `drop_down_url` = '' WHERE `id` = 517;
UPDATE `common_grid_column_template` SET `grid_id` = 51, `field` = 'checkbox', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'checkbox', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 518;
UPDATE `common_grid_column_template` SET `grid_id` = 49, `field` = 'creditNote.creditBalance', `header` = 'Credit Balance', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Credit Balance', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 519;
UPDATE `common_grid_column_template` SET `grid_id` = 14, `field` = 'bill.creditAmount', `header` = 'Credit Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Credit Amount', `column_order` = 25, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 520;
UPDATE `common_grid_column_template` SET `grid_id` = 52, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 521;
UPDATE `common_grid_column_template` SET `grid_id` = 52, `field` = 'sup.custTicketId', `header` = 'Ticket No.', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Ticket No.', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 522;
UPDATE `common_grid_column_template` SET `grid_id` = 52, `field` = 'sup.summary', `header` = 'Summary', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Summary', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 523;
UPDATE `common_grid_column_template` SET `grid_id` = 52, `field` = 'sup.description', `header` = 'Description', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Description', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 524;
UPDATE `common_grid_column_template` SET `grid_id` = 52, `field` = 'sup.createdOn', `header` = 'Created Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Created Date', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 525;
UPDATE `common_grid_column_template` SET `grid_id` = 52, `field` = 'sup.status', `header` = 'Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Status', `column_order` = 6, `drop_down_id` = 29, `drop_down_url` = '' WHERE `id` = 526;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'checkbox', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'checkbox', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 527;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 528;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'receipt.cardNo', `header` = 'Card Number', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'input', `placeholder` = 'Card Number', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 529;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'receipt.transactionDate', `header` = 'Transaction Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Transaction Date', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 530;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'receipt.amount', `header` = 'Transaction Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Transaction Amount', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 531;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'receipt.merchant', `header` = 'Merchant', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Merchant', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 532;
UPDATE `common_grid_column_template` SET `grid_id` = 53, `field` = 'receipt.description', `header` = 'Description', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Description', `column_order` = 7, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 533;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'checkbox', `header` = '', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'checkbox', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 534;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 535;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.transactionDate', `header` = 'Transaction Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Transaction Date', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 536;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.postingDate', `header` = 'Posting Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Posting Date', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 537;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.merchant', `header` = 'Merchant', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Merchant', `column_order` = 7, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 538;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.cardNo', `header` = 'Card Number', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Card Number', `column_order` = 13, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 539;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.description', `header` = 'Description', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Description', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 540;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.amount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 9, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 541;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.status', `header` = 'Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Status', `column_order` = 14, `drop_down_id` = 28, `drop_down_url` = '' WHERE `id` = 542;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.account', `header` = 'Account', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Account', `column_order` = 10, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 543;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.projectCode', `header` = 'Project / Task', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Project Code', `column_order` = 11, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 544;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.missingReceiptAvailability', `header` = 'Missing Receipt', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = '', `placeholder` = 'Missing Receipt', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 545;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.receipt', `header` = 'Receipt', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Receipt', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 546;
UPDATE `common_grid_column_template` SET `grid_id` = 54, `field` = 'transaction.billable', `header` = 'Billable', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Billable', `column_order` = 12, `drop_down_id` = 20, `drop_down_url` = '' WHERE `id` = 547;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'checkbox', `header` = '', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'checkbox', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 548;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 549;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.transactionDate', `header` = 'Transaction Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Transaction Date', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 550;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.postingDate', `header` = 'Posting Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Posting Date', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 551;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.merchant', `header` = 'Merchant', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Merchant', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 552;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.cardNo', `header` = 'Card Number', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Card Number', `column_order` = 14, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 553;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.description', `header` = 'Description', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Description', `column_order` = 9, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 554;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.amount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 10, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 555;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.employeeId', `header` = 'Employee', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Employee', `column_order` = 7, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 556;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.account', `header` = 'Account', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Account', `column_order` = 11, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 557;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.projectCode', `header` = 'Project / Task', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Project Code', `column_order` = 12, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 558;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.missingReceiptAvailability', `header` = 'Missing Receipt', `column_show` = 0, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = '', `placeholder` = 'Missing Receipt', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 559;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.receipt', `header` = 'Receipt', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Receipt', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 560;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.billable', `header` = 'Billable', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Billable', `column_order` = 13, `drop_down_id` = 20, `drop_down_url` = '' WHERE `id` = 561;
UPDATE `common_grid_column_template` SET `grid_id` = 49, `field` = 'creditNote.status', `header` = 'Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Status', `column_order` = 15, `drop_down_id` = 30, `drop_down_url` = '' WHERE `id` = 562;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.remarks', `header` = 'Comment', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Comment', `column_order` = 17, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 563;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approvalUserName', `header` = 'Approval User', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approval User', `column_order` = 18, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 564;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approvedDate', `header` = 'Approved Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Approved Date', `column_order` = 20, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 565;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approvalGroup', `header` = 'Approve Group', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approve Group', `column_order` = 19, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 566;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approver', `header` = 'Next Assignee', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Next Assignee', `column_order` = 16, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 567;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'checkbox', `header` = '', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'checkbox', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 568;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 569;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.transactionDate', `header` = 'Transaction Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Transaction Date', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 570;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.postingDate', `header` = 'Posting Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Posting Date', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 571;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.merchant', `header` = 'Merchant', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Merchant', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 572;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.cardNo', `header` = 'Card Number', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Card Number', `column_order` = 14, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 573;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.description', `header` = 'Description', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Description', `column_order` = 9, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 574;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.amount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 10, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 575;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.employeeId', `header` = 'Employee', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Employee', `column_order` = 7, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 576;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.account', `header` = 'Account', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Account', `column_order` = 11, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 577;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.projectCode', `header` = 'Project / Task', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Project Code', `column_order` = 12, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 578;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.missingReceiptAvailability', `header` = 'Missing Receipt', `column_show` = 0, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = '', `placeholder` = 'Missing Receipt', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 579;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.receipt', `header` = 'Receipt', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Receipt', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 580;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.billable', `header` = 'Billable', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Billable', `column_order` = 13, `drop_down_id` = 20, `drop_down_url` = '' WHERE `id` = 581;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.remarks', `header` = 'Comment', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Comment', `column_order` = 17, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 582;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.approvalUserName', `header` = 'Approval User', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approval User', `column_order` = 18, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 583;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.approvedDate', `header` = 'Approved Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Approved Date', `column_order` = 20, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 584;
UPDATE `common_grid_column_template` SET `grid_id` = 56, `field` = 'transaction.approvalGroup', `header` = 'Approve Group', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approve Group', `column_order` = 19, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 585;

















