----hashila--2.6.32--

UPDATE `common_grid_column_template` SET `grid_id` = 50, `field` = 'statement.totalRecords', `header` = 'Total Records', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Total Records', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `field` = 'statement.totalRecords';


DELETE FROM `common_grid_column_user_wice` WHERE `grid_id` = 50;

UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.remarks', `header` = 'Comment', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Comment', `column_order` = 15, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `field` = 'transaction.remarks' AND `grid_id` = 54;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approvalUserName', `header` = 'Approval User', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approval User', `column_order` = 16, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `field` = 'transaction.approvalUserName' AND `grid_id` = 54;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approvedDate', `header` = 'Approved Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Approved Date', `column_order` = 18, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `field` = 'transaction.approvedDate' AND `grid_id` = 54;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approvalGroup', `header` = 'Approve Group', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approve Group', `column_order` = 17, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `field` = 'transaction.approvalGroup' AND `grid_id` = 54;
UPDATE `common_grid_column_template` SET `grid_id` = 55, `field` = 'transaction.approver', `header` = 'Approver', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = '', `placeholder` = 'Approver', `column_order` = 19, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `field` = 'transaction.approver' AND `grid_id` = 54;
