-------------Amal---------2.3.24-----------------

INSERT INTO `vendor_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`, `hierachy`) VALUES (1021, 'Bill Templates', 'Bill Templates', 'fa fa-file-image-o', 'invoices', '3', 'S', 1008, NULL, 'Admin', 2, 'fa fa-file-image-o', 'Bill Templates', 'Bill Templates', 'A', 0, 1, 1, 'V2', 'BILL_TEMPLATES', 0, 'admin', '2021-11-22 11:59:33', NULL, NULL, NULL, NULL, '1008');

INSERT INTO `vendor_privilages` (`id`, `url`, `text`, `auth_code`, `created_on`, `created_by`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (52, 'Download attachments', 'Download Attachments', 'DOWNLOAD_ATTACHMENTS', '2021-09-30 03:54:36', 'System', NULL, NULL, NULL, NULL);

INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (200, 1021, 1, 'BILL_TEMPLATES_CREATE', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (201, 1021, 4, 'BILL_TEMPLATES_EDIT', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (202, 1021, 14, 'BILL_TEMPLATES_ACTIVATE', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (203, 1021, 13, 'BILL_TEMPLATES_INACTIVATE', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (204, 1021, 5, 'BILL_TEMPLATES_DELETE', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (205, 1021, 3, 'BILL_TEMPLATES_DETAIL_VIEW', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
INSERT INTO `vendor_menu_privilage` (`id`, `menu_id`, `prililage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (208, 1021, 52, 'BILL_TEMPLATES_DOWNLOAD', 'admin', '2021-11-22 11:59:00', NULL, NULL, NULL, NULL);
