---------------Hashila-----------2.1.129--------------------

UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'expand', `header` = '', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'expand', `placeholder` = '', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 347;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'action', `header` = 'Action', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'actionButton', `placeholder` = '', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 348;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.tpBatchId', `header` = 'Batch ID', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Batch Id', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 349;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.createdOn', `header` = 'Created Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Created Date', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 350;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.totalAmount', `header` = 'Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Amount', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 351;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.noOfVendor', `header` = 'No. of Vendors', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'No. of Vendors', `column_order` = 7, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 352;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.noOfBills', `header` = 'No. of Bills', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'No. of Bills', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 353;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.timeToCancel', `header` = 'Time Left to cancel', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'time', `placeholder` = 'Time Left to cancel', `column_order` = 9, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 354;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.status', `header` = 'Approval Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Approval Status', `column_order` = 10, `drop_down_id` = 26, `drop_down_url` = '' WHERE `id` = 355;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.paymentStatus', `header` = 'Payment Status', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Payment Status', `column_order` = 11, `drop_down_id` = 25, `drop_down_url` = '' WHERE `id` = 356;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.providerId', `header` = 'Payment Provider', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'dropdown', `placeholder` = 'Payment Provider', `column_order` = 12, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 357;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.createdBy', `header` = 'Created By', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Created By', `column_order` = 13, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 358;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.approvalUserName', `header` = 'Approval User', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Approved By', `column_order` = 14, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 359;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.approvedDate', `header` = 'Approve Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Approved Date', `column_order` = 15, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 360;
UPDATE `common_grid_column_template` SET `grid_id` = 36, `field` = 'batch.processedDate', `header` = 'Processed Date', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'center', `search_type` = 'date', `placeholder` = 'Processed Date', `column_order` = 16, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 361;

INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (467, 36, 'checkbox', NULL, 1, 0, 0, 0, 0, 'center', 'checkbox', '', 1, NULL, '');

UPDATE `common_grid_state_template` SET `grid_id` = 36, `start_from` = 0, `total_rows` = 10, `column_widths` = '50,50,100,210,210,210,210,210,210,210,210,210,210,210,210,210' WHERE `id` = 36;
