---------Hashila-----------------2.1.144-------------------------------

UPDATE `umm_menu` SET `name` = 'Offline Payments', `display_text` = 'Offline Payments', `menu_style` = 'fa fa-list-alt', `url` = '/home/payments', `tab` = '3', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 3, `display_icon` = 'fa fa-list-alt', `short_name` = 'Offline Payments', `detail_text` = 'Offline Payments', `status` = 'A', `portal_menu` = 1, `individual_tenant_menu` = 1, `vendor_community_menu` = 1, `version` = 'V2', `auth_code` = 'BILL_PAYMENT', `slim_menu` = 0, `hierachy` = '1005,1029', `created_by` = 'System', `created_on` = '2021-09-27 11:58:12', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1020;

INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1032, 'Payments', 'Payments', 'fa fa-credit-card', '/home/payments', '0', 'S', 1029, NULL, 'Admin', 13, 'fa fa-credit-card', 'Payments', 'Payments', 'A', 0, 1, 0, 'V2', 'PAYMENTS', 1, '1005,1015', 'System', '2021-09-06 05:48:40', NULL, NULL, NULL, NULL);

UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 3, `auth_code` = 'PAYMENT_DETAIL_VIEW', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 401;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 6, `auth_code` = 'PAYMENT_APPROVE', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 402;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 7, `auth_code` = 'PAYMENT_REJECT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 403;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 11, `auth_code` = 'PAYMENT_SUBMIT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 404;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 93, `auth_code` = 'PAYMENT_PAY_NOW', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 405;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 94, `auth_code` = 'PAYMENT_MAKE_AN_OFFLINE_PAYMENT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 406;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 95, `auth_code` = 'PAYMENT_SCHEDULE_PAYMENT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 407;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 96, `auth_code` = 'PAYMENT_CANCEL_BATCH_PAYMENT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 408;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 40, `auth_code` = 'PAYMENT_OVERRIDE_APPROVAL', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 409;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 98, `auth_code` = 'PAYMENT_DOWNLOAD_ATTACHMENT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 423;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 101, `auth_code` = 'PAYMENT_VIEW_SUMMARY', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 424;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 10, `auth_code` = 'PAYMENT_VIEW_AUDIT_TRIAL', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 425;

INSERT INTO `umm_role_previlege` (`role_id`, `privilege_id`, `sub_account_id`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1, 1032, NULL, 'System', '2021-09-27 12:11:29', NULL, NULL, NULL, NULL);

UPDATE `umm_menu` SET `name` = 'Payments', `display_text` = 'Payments', `menu_style` = 'fa fa-credit-card', `url` = '/home/payments', `tab` = '0', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 13, `display_icon` = 'fa fa-credit-card', `short_name` = 'Payments', `detail_text` = 'Payments', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENTS', `slim_menu` = 0, `hierachy` = '1005,1015', `created_by` = 'System', `created_on` = '2021-09-27 13:03:00', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1032;
