----------------------Niron-----------2.2.19-----------------

UPDATE `common_grid_column_template` SET `id`='328', `grid_id`='33', `field`='txn.batchId', `header`='Batch ID', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Batch ID', `column_order`='1', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='328');
UPDATE `common_grid_column_template` SET `id`='329', `grid_id`='33', `field`='txn.txnRef', `header`='Reference Number', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Transaction Id', `column_order`='2', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='329');
UPDATE `common_grid_column_template` SET `id`='331', `grid_id`='33', `field`='txn.paidAmount', `header`='Paid Amount', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='right', `search_type`='numeric', `placeholder`='Paid Amount', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='331');
UPDATE `common_grid_column_template` SET `id`='332', `grid_id`='33', `field`='txn.txnDate', `header`='Transaction Date', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='date', `placeholder`='Transaction Date', `column_order`='7', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='332');
UPDATE `common_grid_column_template` SET `id`='333', `grid_id`='33', `field`='txn.paymentDate', `header`='Payment Date', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='date', `placeholder`='Payment Date', `column_order`='4', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='333');
UPDATE `common_grid_column_template` SET `id`='394', `grid_id`='33', `field`='txn.approvalStatus', `header`='Approval Status', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='dropdown', `placeholder`='Approval Status', `column_order`='5', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='394');
UPDATE `common_grid_column_template` SET `id`='395', `grid_id`='33', `field`='txn.paymentType', `header`='Transaction Type', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='dropdown', `placeholder`='Transaction Type', `column_order`='8', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='395');
UPDATE `common_grid_column_template` SET `id`='396', `grid_id`='33', `field`='txn.reason', `header`='Reason (If failed)', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Reason (If Faild)', `column_order`='9', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='396');
UPDATE `common_grid_column_template` SET `id`='450', `grid_id`='33', `field`='txn.paymentStatus', `header`='Payment Status', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='input', `placeholder`='Payment Status', `column_order`='6', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='450');

UPDATE `common_grid_state_template` SET `id`='32', `grid_id`='32', `start_from`='0', `total_rows`='10', `column_widths`='50,50,100,210,210,135,135,180,180,180,180,210,210,180,210,210,145' WHERE (`id`='32');
UPDATE `common_grid_column_template` SET `id`='327', `grid_id`='32', `field`='bill.referenceNo', `header`='Reference Number', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Reference No', `column_order`='12', `drop_down_id`=NULL, `drop_down_url`=NULL WHERE (`id`='327');
UPDATE `common_grid_column_template` SET `id`='395', `grid_id`='33', `field`='txn.paymentType', `header`='Transaction Type', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='dropdown', `placeholder`='Transaction Type', `column_order`='8', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='395');
UPDATE `common_grid_state_template` SET `id`='36', `grid_id`='36', `start_from`='0', `total_rows`='10', `column_widths`='50,50,100,210,135,180,145,145,160,145,145,210,210,210,135,135' WHERE (`id`='36');
UPDATE `common_grid_column_template` SET `id`='360', `grid_id`='36', `field`='batch.approvedDate', `header`='Approved Date', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='center', `search_type`='date', `placeholder`='Approved Date', `column_order`='15', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='360');
UPDATE `common_grid_column_template` SET `id`='430', `grid_id`='43', `field`='bill.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Billl No', `column_order`='2', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='430');
UPDATE `common_grid_state_template` SET `id`='43', `grid_id`='43', `start_from`='0', `total_rows`='10', `column_widths`='50,210,135,180,180,180,180,135' WHERE (`id`='43');
UPDATE `common_grid_column_template` SET `id`='439', `grid_id`='44', `field`='txn.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Bill No', `column_order`='1', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='439');
UPDATE `common_grid_column_template` SET `id`='440', `grid_id`='44', `field`='txn.txnRef', `header`='Payment Reference No.', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Payment Reference No', `column_order`='2', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='440');
UPDATE `common_grid_column_template` SET `id`='52', `grid_id`='7', `field`='vi.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Bill No.', `column_order`='7', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='52');
UPDATE `common_grid_column_template` SET `id`='83', `grid_id`='7', `field`='vi.poId', `header`='PO No.', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='dropdown', `placeholder`='PO No', `column_order`='12', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='83');
UPDATE `common_grid_column_template` SET `id`='341', `grid_id`='35', `field`='txn.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Bill No', `column_order`='1', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='341');
UPDATE `common_grid_column_template` SET `id`='399', `grid_id`='35', `field`='txn.txnRef', `header`='Reference Number', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Reference No', `column_order`='7', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='399');
UPDATE `common_grid_column_template` SET `id`='359', `grid_id`='36', `field`='batch.approvalUserName', `header`='Approval User', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Approval User', `column_order`='14', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='359');
UPDATE `common_grid_column_template` SET `id`='416', `grid_id`='42', `field`='txn.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Bill No', `column_order`='1', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='416');
UPDATE `common_grid_column_template` SET `id`='421', `grid_id`='42', `field`='txn.txnRef', `header`='Reference Number', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Reference No', `column_order`='7', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='421');
UPDATE `common_grid_column_template` SET `id`='465', `grid_id`='45', `field`='bill.referenceNo', `header`='Reference Number', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Reference No', `column_order`='10', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='465');

UPDATE `common_grid_column_template` SET `id`='453', `grid_id`='45', `field`='bill.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Bill Number', `column_order`='4', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='453');
UPDATE `common_grid_column_template` SET `id`='460', `grid_id`='45', `field`='bill.applicableDiscount', `header`='Applicable Discount', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='right', `search_type`='input', `placeholder`='Applied Discount', `column_order`='15', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='460');
UPDATE `common_grid_column_template` SET `id`='357', `grid_id`='36', `field`='batch.providerId', `header`='Payment Provider', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='dropdown', `placeholder`='Payment Provider', `column_order`='12', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='357');

UPDATE `common_grid_column_template` SET `id`='362', `grid_id`='37', `field`='txn.txnRef', `header`='Reference Number', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Transaction Id', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='362');
UPDATE `common_grid_column_template` SET `id`='363', `grid_id`='37', `field`='txn.billNo', `header`='Bill No.', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Bill No', `column_order`='2', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='363');
UPDATE `common_grid_column_template` SET `id`='364', `grid_id`='37', `field`='txn.vendor', `header`='Vendor', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Vendor', `column_order`='1', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='364');
UPDATE `common_grid_column_template` SET `id`='365', `grid_id`='37', `field`='txn.paidAmount', `header`='Paid Amount', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='right', `search_type`='numeric', `placeholder`='Paid Amount', `column_order`='4', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='365');
UPDATE `common_grid_column_template` SET `id`='366', `grid_id`='37', `field`='txn.txnDate', `header`='Transaction Date', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='date', `placeholder`='Transaction Date', `column_order`='8', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='366');
UPDATE `common_grid_column_template` SET `id`='367', `grid_id`='37', `field`='txn.paymentDate', `header`='Payment Date', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='date', `placeholder`='Payment Date', `column_order`='5', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='367');
UPDATE `common_grid_column_template` SET `id`='368', `grid_id`='37', `field`='txn.approvalStatus', `header`='Approval Status', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='input', `placeholder`='Approval Status', `column_order`='6', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='368');
UPDATE `common_grid_column_template` SET `id`='369', `grid_id`='37', `field`='txn.paymentType', `header`='Transaction Type', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Transaction Type', `column_order`='9', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='369');
UPDATE `common_grid_column_template` SET `id`='370', `grid_id`='37', `field`='txn.reason', `header`='Reason (If failed)', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Reason (If Faild)', `column_order`='10', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='370');
UPDATE `common_grid_column_template` SET `id`='445', `grid_id`='37', `field`='txn.paymentStatus', `header`='Payment Status', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='center', `search_type`='input', `placeholder`='Payment Status', `column_order`='7', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='445');
UPDATE `common_grid_state_template` SET `id`='45', `grid_id`='45', `start_from`='0', `total_rows`='10', `column_widths`='50,210,210,135,135,180,180,180,210,180,210,180,210,210,145' WHERE (`id`='45');







