----------Hashila----------2.1.87----------------

UPDATE `common_grid_column_template` SET `grid_id` = 41, `field` = 'pay.vendor', `header` = 'Vendor', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'left', `search_type` = 'input', `placeholder` = 'Vendor', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 411;
UPDATE `common_grid_column_template` SET `grid_id` = 41, `field` = 'pay.noOfBills', `header` = 'No. of Bills', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'number', `placeholder` = 'No. of Bills', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 412;
UPDATE `common_grid_column_template` SET `grid_id` = 41, `field` = 'pay.paidAmount', `header` = 'Paid Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'right', `search_type` = 'number', `placeholder` = 'Paid Amount', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 413;
UPDATE `common_grid_column_template` SET `grid_id` = 41, `field` = 'pay.appliedDiscount', `header` = 'Applied Discount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'right', `search_type` = 'number', `placeholder` = 'Applied Discount', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 414;
UPDATE `common_grid_column_template` SET `grid_id` = 41, `field` = 'expand', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'expand', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 415;


UPDATE `common_grid_column_template` SET `grid_id` = 34, `field` = 'pay.vendor', `header` = 'Vendor', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'left', `search_type` = 'input', `placeholder` = 'Vendor', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 335;
UPDATE `common_grid_column_template` SET `grid_id` = 34, `field` = 'pay.noOfBills', `header` = 'No. of Bills', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'No. of Bills', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 336;
UPDATE `common_grid_column_template` SET `grid_id` = 34, `field` = 'pay.paymentAmount', `header` = 'Payment Amount', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Payment Amount', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 337;
UPDATE `common_grid_column_template` SET `grid_id` = 34, `field` = 'pay.balanceToBePaid', `header` = 'Balance to be Paid', `column_show` = 1, `is_sortable` = 1, `is_re_orderable` = 1, `is_re_sizable` = 1, `can_hide` = 1, `align` = 'right', `search_type` = 'numeric', `placeholder` = 'Balance to be Paid', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 338;
UPDATE `common_grid_column_template` SET `grid_id` = 34, `field` = 'expand', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'expand', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 339;
UPDATE `common_grid_column_template` SET `grid_id` = 34, `field` = 'delete', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'deleteButton', `placeholder` = '', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 340;
