---------------Hashila------2.1.128---------

INSERT INTO `common_grid_template` (`id`, `grid_name`) VALUES (45, 'PAYMENT_ADD_BILLS');


INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (451, 45, 'checkbox', '', 1, 0, 0, 0, 0, 'center', 'checkbox', '', 1, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (452, 45, 'vendor.name', 'Vendor', 1, 1, 1, 1, 1, 'left', 'multiSelect', 'Vendor', 3, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (453, 45, 'bill.billNo', 'Bill Number', 1, 1, 1, 1, 1, 'left', 'input', 'Bill Number', 4, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (454, 45, 'bill.billDate', 'Bill Date', 1, 1, 1, 1, 1, 'center', 'date', 'Bill Date', 5, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (455, 45, 'bill.billAmount', 'Amount', 1, 1, 1, 1, 1, 'right', 'numeric', 'Amount', 7, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (456, 45, 'bill.paidAmount', 'Paid Amount', 1, 1, 1, 1, 1, 'right', 'numeric', 'Paid Amount', 8, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (457, 45, 'bill.balanceAmount', 'Balance Amount', 1, 0, 1, 1, 1, 'right', 'numeric', 'Balance Amount', 11, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (458, 45, 'bill.paymentType', 'Payment Type', 1, 0, 1, 1, 1, 'left', 'input', 'Payment Type', 12, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (459, 45, 'bill.paymentAmount', 'Payment Amount', 1, 0, 1, 1, 1, 'right', 'numeric', 'Payment Amount', 13, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (460, 45, 'bill.applicableDiscount', 'Applicable Discount (If The Payment Date is Today)', 1, 0, 1, 1, 1, 'right', 'input', 'Applied Discount', 15, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (461, 45, 'bill.paymentStatus', 'Payment Status', 1, 1, 1, 1, 1, 'center', 'dropdown', 'Payment Status', 16, 16, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (462, 45, 'bill.dueDate', 'Due Date', 1, 1, 1, 1, 1, 'center', 'date', 'Due Date', 6, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (463, 45, 'comment', 'Comment', 1, 0, 1, 1, 1, 'left', 'input', 'Comment', 14, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (464, 45, 'expand', '', 1, 0, 0, 0, 0, 'center', 'expand', '', 2, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (465, 45, 'bill.referenceNo', 'Reference No', 1, 0, 1, 1, 1, 'left', 'input', 'Reference No', 10, NULL, '');
INSERT INTO `common_grid_column_template` (`id`, `grid_id`, `field`, `header`, `column_show`, `is_sortable`, `is_re_orderable`, `is_re_sizable`, `can_hide`, `align`, `search_type`, `placeholder`, `column_order`, `drop_down_id`, `drop_down_url`) VALUES (466, 45, 'bill.paymentUnderProcessing', 'Payment Under Processing', 1, 1, 1, 1, 1, 'right', 'numeric', 'Payment Under Processing', 9, NULL, '');

INSERT INTO `common_grid_state_template` (`id`, `grid_id`, `start_from`, `total_rows`, `column_widths`) VALUES (45, 45, 0, 10, '50,50,210,210,210,210,210,210,210,210,210,210,210,210,320,210');
