-----------------Hashila-------2.2.2--------------

UPDATE `umm_menu` SET `name` = 'Approved Bills', `display_text` = 'Approved Bills', `menu_style` = 'fa fa-check-square-o', `url` = '/home/payments', `tab` = '0', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 1, `display_icon` = 'fa fa-check-square-o', `short_name` = 'Approved Bills', `detail_text` = 'Approved Bills', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENTS', `slim_menu` = 0, `hierachy` = '1005,1015', `created_by` = 'System', `created_on` = '2021-09-27 15:23:52', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1032;

INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1033, 'Batch Payments', 'Batch Payments', 'fa fa-sitemap', '/home/payments', '1', 'S', 1029, NULL, 'Admin', 2, 'fa fa-sitemap', 'Batch Payments', 'Batch Payments', 'A', 0, 1, 0, 'V2', 'PAYMENTS_BATCH', 0, '1005,1015', 'System', '2021-09-27 15:23:52', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu` (`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1034, 'Vendor Payments', 'Vendor Payments', 'fa fa-handshake-o', '/home/payments', '2', 'S', 1029, NULL, 'Admin', 3, 'fa fa-handshake-o', 'Vendor Payments', 'Vendor Payments', 'A', 0, 1, 0, 'V2', 'PAYMENTS_VENDOR', 0, '1005,1015', 'System', '2021-09-27 15:23:52', NULL, NULL, NULL, NULL);


UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 3, `auth_code` = 'PAYMENT_DETAIL_VIEW', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 401;
UPDATE `umm_menu_privilage` SET `menu_id` = 1033, `privilage_id` = 6, `auth_code` = 'PAYMENT_APPROVE', `created_by` = 'System', `created_on` = '2021-09-27 14:36:55', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 402;
UPDATE `umm_menu_privilage` SET `menu_id` = 1033, `privilage_id` = 7, `auth_code` = 'PAYMENT_REJECT', `created_by` = 'System', `created_on` = '2021-09-27 14:36:58', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 403;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 11, `auth_code` = 'PAYMENT_SUBMIT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 404;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 93, `auth_code` = 'PAYMENT_PAY_NOW', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 405;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 95, `auth_code` = 'PAYMENT_SCHEDULE_PAYMENT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 407;
UPDATE `umm_menu_privilage` SET `menu_id` = 1033, `privilage_id` = 96, `auth_code` = 'PAYMENT_CANCEL_BATCH_PAYMENT', `created_by` = 'System', `created_on` = '2021-09-27 14:37:27', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 408;
UPDATE `umm_menu_privilage` SET `menu_id` = 1033, `privilage_id` = 40, `auth_code` = 'PAYMENT_OVERRIDE_APPROVAL', `created_by` = 'System', `created_on` = '2021-09-27 14:37:42', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 409;
UPDATE `umm_menu_privilage` SET `menu_id` = 1032, `privilage_id` = 98, `auth_code` = 'PAYMENT_DOWNLOAD_ATTACHMENT', `created_by` = 'System', `created_on` = '2021-09-27 11:57:32', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 423;
UPDATE `umm_menu_privilage` SET `menu_id` = 1034, `privilage_id` = 101, `auth_code` = 'PAYMENT_VIEW_SUMMARY', `created_by` = 'System', `created_on` = '2021-09-27 14:31:39', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 424;
UPDATE `umm_menu_privilage` SET `menu_id` = 1033, `privilage_id` = 10, `auth_code` = 'PAYMENT_VIEW_AUDIT_TRIAL', `created_by` = 'System', `created_on` = '2021-09-27 14:40:38', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 425;

UPDATE `umm_menu_privilage` SET `menu_id` = 1033, `privilage_id` = 3, `auth_code` = 'PAYMENT_BATCH_DETAIL_VIEW', `created_by` = 'System', `created_on` = '2021-09-27 14:43:19', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 406;

INSERT INTO `umm_role_previlege` (`role_id`, `privilege_id`, `sub_account_id`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1, 1033, NULL, 'System', '2021-09-27 14:53:00', NULL, NULL, NULL, NULL);
INSERT INTO `umm_role_previlege` (`role_id`, `privilege_id`, `sub_account_id`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1, 1034, NULL, 'System', '2021-09-27 14:52:54', NULL, NULL, NULL, NULL);


UPDATE `umm_menu` SET `name` = 'Payments', `display_text` = 'Payments', `menu_style` = 'fa fa-credit-card', `url` = '/home/payments', `tab` = '0', `type` = 'S', `super_type` = 1015, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 4, `display_icon` = 'fa fa-credit-card', `short_name` = 'Payments', `detail_text` = 'Payments', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENTS', `slim_menu` = 1, `hierachy` = '1005,1015', `created_by` = 'System', `created_on` = '2021-09-27 14:57:13', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1029;

UPDATE `umm_menu` SET `name` = 'Expenses', `display_text` = 'Expenses', `menu_style` = 'fa fa-usd', `url` = '/home/expense', `tab` = NULL, `type` = 'S', `super_type` = 1015, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 5, `display_icon` = 'fa fa-usd', `short_name` = 'Expenses', `detail_text` = 'Expenses', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'EXPENSES', `slim_menu` = 1, `hierachy` = '1015', `created_by` = 'System', `created_on` = '2021-09-27 14:57:16', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1007;


UPDATE `umm_menu` SET `name` = 'Offline Payments', `display_text` = 'Offline Payments', `menu_style` = 'fa fa-list-alt', `url` = '/home/payments', `tab` = '3', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 3, `display_icon` = 'fa fa-list-alt', `short_name` = 'Offline Payments', `detail_text` = 'Offline Payments', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENT_OFFLINE_PAYMENT', `slim_menu` = 0, `hierachy` = '1005,1029', `created_by` = 'System', `created_on` = '2021-09-27 16:38:46', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1020;

UPDATE `umm_menu` SET `name` = 'Approved Bills', `display_text` = 'Approved Bills', `menu_style` = 'fa fa-check-square-o', `url` = '/home/payments', `tab` = '0', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 1, `display_icon` = 'fa fa-check-square-o', `short_name` = 'Approved Bills', `detail_text` = 'Approved Bills', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENT_APPROVED_BILLS', `slim_menu` = 0, `hierachy` = '1005,1029', `created_by` = 'System', `created_on` = '2021-09-27 17:23:09', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1032;
UPDATE `umm_menu` SET `name` = 'Batch Payments', `display_text` = 'Batch Payments', `menu_style` = 'fa fa-sitemap', `url` = '/home/payments', `tab` = '1', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 2, `display_icon` = 'fa fa-sitemap', `short_name` = 'Batch Payments', `detail_text` = 'Batch Payments', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENT_BATCH', `slim_menu` = 0, `hierachy` = '1005,1029', `created_by` = 'System', `created_on` = '2021-09-27 17:23:05', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1033;
UPDATE `umm_menu` SET `name` = 'Vendor Payments', `display_text` = 'Vendor Payments', `menu_style` = 'fa fa-handshake-o', `url` = '/home/payments', `tab` = '2', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 3, `display_icon` = 'fa fa-handshake-o', `short_name` = 'Vendor Payments', `detail_text` = 'Vendor Payments', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENT_VENDOR', `slim_menu` = 0, `hierachy` = '1005,1029', `created_by` = 'System', `created_on` = '2021-09-27 17:23:07', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1034;

UPDATE `umm_menu` SET `name` = 'Payments', `display_text` = 'Payments', `menu_style` = 'fa fa-credit-card', `url` = '/home/payments', `tab` = '0', `type` = 'S', `super_type` = 1015, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 4, `display_icon` = 'fa fa-credit-card', `short_name` = 'Payments', `detail_text` = 'Payments', `status` = 'A', `portal_menu` = 1, `individual_tenant_menu` = 1, `vendor_community_menu` = 1, `version` = 'V2', `auth_code` = 'PAYMENT', `slim_menu` = 1, `hierachy` = '1005,1015', `created_by` = 'System', `created_on` = '2021-09-27 17:23:01', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1029;

UPDATE `umm_menu` SET `name` = 'Offline Payments', `display_text` = 'Offline Payments', `menu_style` = 'fa fa-list-alt', `url` = '/home/payments', `tab` = '3', `type` = 'S', `super_type` = 1029, `super_type_2` = NULL, `department` = 'Admin', `menu_order` = 3, `display_icon` = 'fa fa-list-alt', `short_name` = 'Offline Payments', `detail_text` = 'Offline Payments', `status` = 'A', `portal_menu` = 0, `individual_tenant_menu` = 1, `vendor_community_menu` = 0, `version` = 'V2', `auth_code` = 'PAYMENT_OFFLINE_PAYMENT', `slim_menu` = 0, `hierachy` = '1005,1029', `created_by` = 'System', `created_on` = '2021-09-27 16:38:46', `update_by` = NULL, `update_on` = NULL, `delete_by` = NULL, `delete_on` = NULL WHERE `id` = 1020;
