--------------Hashila----------2.2.11------------

UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.billNo', `header` = 'Bill No', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'left', `search_type` = 'input', `placeholder` = 'Billl No', `column_order` = 2, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 430;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'expand', `header` = NULL, `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'expand', `placeholder` = '', `column_order` = 1, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 431;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.billDate', `header` = 'Bill Date', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'date', `placeholder` = 'Bill Date', `column_order` = 3, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 432;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.billAmount', `header` = 'Bill Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'right', `search_type` = 'number', `placeholder` = 'Bill Amount', `column_order` = 4, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 433;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.paidAmount', `header` = 'Paid Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'right', `search_type` = 'number', `placeholder` = 'Paid Amount', `column_order` = 5, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 434;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.balanceAmount', `header` = 'Balance Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'right', `search_type` = 'number', `placeholder` = 'Balance Amount', `column_order` = 6, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 435;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.discountAmount', `header` = 'Discount Amount', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'right', `search_type` = 'number', `placeholder` = 'Discount Amount', `column_order` = 7, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 436;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.discountApplicableDate', `header` = 'Discount Applicable Date', `column_show` = 0, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'date', `placeholder` = 'Discount Applicable Date', `column_order` = 8, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 437;
UPDATE `common_grid_column_template` SET `grid_id` = 43, `field` = 'bill.dueDate', `header` = 'Due Date', `column_show` = 1, `is_sortable` = 0, `is_re_orderable` = 0, `is_re_sizable` = 0, `can_hide` = 0, `align` = 'center', `search_type` = 'date', `placeholder` = 'Due Date', `column_order` = 9, `drop_down_id` = NULL, `drop_down_url` = '' WHERE `id` = 438;

UPDATE `common_grid_column_template` SET `id`='322', `grid_id`='32', `field`='bill.applicableDiscount', `header`='Applicable Discount', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Applied Discount', `column_order`='15', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='322');
UPDATE `common_grid_column_template` SET `id`='354', `grid_id`='36', `field`='batch.timeToCancel', `header`='Time Left to Cancel', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='center', `search_type`='time', `placeholder`='Time Left to cancel', `column_order`='9', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='354');
UPDATE `common_grid_column_template` SET `id`='349', `grid_id`='36', `field`='batch.tpBatchId', `header`='Batch ID', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Batch ID', `column_order`='4', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='349');
UPDATE `common_grid_column_template` SET `id`='369', `grid_id`='37', `field`='txn.paymentType', `header`='Transaction Type', `column_show`='1', `is_sortable`='0', `is_re_orderable`='0', `is_re_sizable`='0', `can_hide`='0', `align`='left', `search_type`='input', `placeholder`='Transaction Type', `column_order`='3', `drop_down_id`=NULL, `drop_down_url`='' WHERE (`id`='369');
UPDATE `common_grid_column_template` SET `id`='327', `grid_id`='32', `field`='bill.referenceNo', `header`='Reference No', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Reference No', `column_order`='12', `drop_down_id`=NULL, `drop_down_url`=NULL WHERE (`id`='327');
UPDATE `common_grid_column_template` SET `id`='320', `grid_id`='32', `field`='bill.paymentType', `header`='Payment Type', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Payment Type', `column_order`='13', `drop_down_id`=NULL, `drop_down_url`=NULL WHERE (`id`='320');
UPDATE `common_grid_column_template` SET `id`='321', `grid_id`='32', `field`='bill.paymentAmount', `header`='Payment Amount', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='right', `search_type`='numeric', `placeholder`='Payment Amount', `column_order`='14', `drop_down_id`=NULL, `drop_down_url`=NULL WHERE (`id`='321');
UPDATE `common_grid_column_template` SET `id`='325', `grid_id`='32', `field`='comment', `header`='Comment', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Comment', `column_order`='15', `drop_down_id`=NULL, `drop_down_url`=NULL WHERE (`id`='325');
UPDATE `common_grid_column_template` SET `id`='322', `grid_id`='32', `field`='bill.applicableDiscount', `header`='Applicable Discount', `column_show`='1', `is_sortable`='0', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='left', `search_type`='input', `placeholder`='Applied Discount', `column_order`='16', `drop_down_id`=NULL, `drop_down_url`=NULL WHERE (`id`='322');
UPDATE `common_grid_column_template` SET `id`='323', `grid_id`='32', `field`='bill.paymentStatus', `header`='Payment Status', `column_show`='1', `is_sortable`='1', `is_re_orderable`='1', `is_re_sizable`='1', `can_hide`='1', `align`='center', `search_type`='dropdown', `placeholder`='Payment Status', `column_order`='17', `drop_down_id`='16', `drop_down_url`=NULL WHERE (`id`='323');

UPDATE `common_grid_state_template` SET `id`='32', `grid_id`='32', `start_from`='0', `total_rows`='10', `column_widths`='50,50,100,210,210,210,210,210,210,210,210,210,210,210,210,320,145' WHERE (`id`='32');
UPDATE `common_grid_state_template` SET `id`='36', `grid_id`='36', `start_from`='0', `total_rows`='10', `column_widths`='50,50,100,210,210,210,210,210,210,145,145,210,210,210,210,210' WHERE (`id`='36');
UPDATE `common_grid_state_template` SET `id`='7', `grid_id`='7', `start_from`='0', `total_rows`='15', `column_widths`='50,100,210,155,155,155,155,155,155,155,155,155,145,145' WHERE (`id`='7');

UPDATE `common_grid_state_template` SET `id`='32', `grid_id`='32', `start_from`='0', `total_rows`='10', `column_widths`='50,50,100,210,210,210,210,210,210,210,210,210,210,210,210,210,145' WHERE (`id`='32');






