--------------Hashila-----2.6.81--------

UPDATE `umm_menu` SET `tab` = '1', `menu_order` = 1, `hierachy` = '1015,1007' WHERE `id` = 1048;

INSERT INTO `umm_privilages`(`id`, `url`, `text`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (133, 'Generate Bill', 'Generate Bill', 'GENERATE_BILL', 'System', '2022-06-09 12:54:59', NULL, NULL, NULL, NULL);

UPDATE `umm_menu` SET `menu_style` = 'pi pi-credit-card' WHERE `id` = 1048;
UPDATE `umm_menu` SET `display_icon` = 'pi pi-credit-card' WHERE `id` = 1048;



INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1051, 'Expenses', 'Expenses', 'fa fa-usd', '/home/expense', '0', 'S', 1007, NULL, 'Admin', 0, 'fa fa-usd', 'Expenses', 'Expenses', 'A', 0, 1, 0, 'V2', 'EXPENSES', 1, '1015,1007', 'System', '2022-06-09 18:09:44', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1052, 'Credit Card', 'Credit Card', 'pi pi-credit-card', '/home/expense', '1', 'S', 1048, NULL, 'Admin', 0, 'pi pi-credit-card', 'Credit Card', 'Credit Card', 'A', 0, 1, 0, 'V2', 'CREDIT_CARD', 0, '1015,1007,1048', 'System', '2022-06-09 18:05:12', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1053, 'Upload Transactions', 'Upload Transactions', 'pi pi-upload', '/home/expense', '1', 'S', 1048, NULL, 'Admin', 1, 'pi pi-upload', 'Upload Transactions', 'Upload Transactions', 'A', 0, 1, 0, 'V2', 'CREDIT_CARD_UPLOAD_TRANSACTIONS', 0, '1015,1007,1048', 'System', '2022-06-09 18:05:22', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1054, 'Process Transactons', 'Process Transactons', 'fa fa-share-square-o', '/home/expense', '1', 'S', 1048, NULL, 'Admin', 2, 'fa fa-share-square-o', 'Process Transactons', 'Process Transactons', 'A', 0, 1, 0, 'V2', 'CREDIT_CARD_PROCESS_TRANSACTIONS', 0, '1015,1007,1048', 'System', '2022-06-09 18:13:16', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1055, 'Submitted Transactions', 'Submitted Transactions', 'pi pi-envelope', '/home/expense', '1', 'S', 1048, NULL, 'Admin', 3, 'pi pi-envelope', 'Submitted Transactions', 'Submitted Transactions', 'A', 0, 1, 0, 'V2', 'CREDIT_CARD_SUBMITTED_TRANSACTIONS', 0, '1015,1007,1048', 'System', '2022-06-09 18:18:17', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1056, 'Approved Transactions', 'Approved Transactions', 'pi pi-check-square', '/home/expense', '1', 'S', 1048, NULL, 'Admin', 4, 'pi pi-check-square', 'Approved Transactions', 'Approved Transactions', 'A', 0, 1, 0, 'V2', 'CREDIT_CARD_APPROVED_TRANSACTIONS', 0, '1015,1007,1048', 'System', '2022-06-09 18:09:02', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu`(`id`, `name`, `display_text`, `menu_style`, `url`, `tab`, `type`, `super_type`, `super_type_2`, `department`, `menu_order`, `display_icon`, `short_name`, `detail_text`, `status`, `portal_menu`, `individual_tenant_menu`, `vendor_community_menu`, `version`, `auth_code`, `slim_menu`, `hierachy`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (1057, 'Receipt', 'Receipt', 'pi pi-book', '/home/expense', '2', 'S', 1007, NULL, 'Admin', 2, 'pi pi-book', 'Receipt', 'Receipt', 'A', 0, 1, 0, 'V2', 'CREDIT_CARD_RECEIPT', 0, '1015,1007', 'System', '2022-06-09 18:07:57', NULL, NULL, NULL, NULL);

INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (490, 1052, 1, 'CREDIT_CARD_CREATE', 'System', '2022-06-09 12:16:06', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (491, 1052, 4, 'CREDIT_CARD_EDIT', 'System', '2022-06-09 12:16:42', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (492, 1052, 14, 'CREDIT_CARD_ACTIVE', 'System', '2022-06-09 13:10:37', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (493, 1052, 13, 'CREDIT_CARD_INACTIVE', 'System', '2022-06-09 13:10:39', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (494, 1052, 5, 'CREDIT_CARD_DELETE', 'System', '2022-06-09 13:10:43', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (495, 1053, 8, 'CREDIT_CARD_UPLOAD_TRANSACTIONS_UPLOAD', 'System', '2022-06-09 14:00:44', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (496, 1053, 4, 'CREDIT_CARD_UPLOAD_TRANSACTIONS_EDIT', 'System', '2022-06-09 14:00:41', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (497, 1054, 1, 'CREDIT_CARD_PROCESS_TRANSACTIONS_CREATE', 'System', '2022-06-09 14:00:39', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (498, 1054, 10, 'CREDIT_CARD_PROCESS_TRANSACTIONS_VIEW_AUDIT_TRIAL', 'System', '2022-06-09 14:00:37', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (499, 1054, 11, 'CREDIT_CARD_PROCESS_TRANSACTIONS_SUBMIT', 'System', '2022-06-09 14:00:34', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (500, 1054, 77, 'CREDIT_CARD_PROCESS_TRANSACTIONS_SAVE_AS_APPROVED', 'System', '2022-06-09 14:00:32', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (501, 1055, 6, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_APPROVE', 'System', '2022-06-09 14:02:01', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (502, 1055, 60, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_QUICK_APPROVE', 'System', '2022-06-09 14:02:03', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (503, 1055, 7, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_REJECT', 'System', '2022-06-09 14:02:05', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (504, 1055, 16, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_CHANGE_ASSIGNEE', 'System', '2022-06-09 14:02:08', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (505, 1055, 38, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_SKIP_APPROVAL', 'System', '2022-06-09 14:01:41', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (506, 1055, 10, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_VIEW_AUDIT_TRIAL', 'System', '2022-06-09 14:01:33', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (507, 1055, 40, 'CREDIT_CARD_SUBMITTED_TRANSACTIONS_OVERRIDE_APPROVAL', 'System', '2022-06-09 14:01:30', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (508, 1056, 133, 'CREDIT_CARD_APPROVED_TRANSACTIONS_GENERATE_BILL', 'System', '2022-06-09 14:01:24', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (509, 1056, 10, 'CREDIT_CARD_APPROVED_TRANSACTIONS_VIEW_AUDIT_TRIAL', 'System', '2022-06-09 14:01:20', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (510, 1057, 8, 'CREDIT_CARD_RECEIPT_UPLOAD', 'System', '2022-06-09 13:59:05', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (511, 1057, 5, 'CREDIT_CARD_RECEIPT_DELETE', 'System', '2022-06-09 13:59:06', NULL, NULL, NULL, NULL);
INSERT INTO `umm_menu_privilage`(`id`, `menu_id`, `privilage_id`, `auth_code`, `created_by`, `created_on`, `update_by`, `update_on`, `delete_by`, `delete_on`) VALUES (512, 1057, 98, 'CREDIT_CARD_RECEIPT_DOWNLOAD_ATTACHMENT', 'System', '2022-06-09 13:59:08', NULL, NULL, NULL, NULL);

UPDATE `umm_menu_privilage` SET `menu_id` = 1051 WHERE `menu_id` = 1007;


